/**
 * Rutas tipo átomo y paquetes de etiquetas que viajan sobre la red.
 */

import { GLOBE_NODES } from './globeNetworkData';
import { buildAtmosphericEnvelope } from './globeAtmosphereTopology';
import {
  GLOBE_PACKET_MAX,
  GLOBE_PACKET_MIN,
  GLOBE_STATIC_LABELS,
} from './globeLabelCatalog';

export { GLOBE_PACKET_MAX, GLOBE_PACKET_MIN, GLOBE_STATIC_LABELS };

const NI = Object.fromEntries(GLOBE_NODES.map((n, i) => [n.id, i]));

function nodePair(from, to) {
  return {
    from,
    to,
    a: NI[from],
    b: NI[to],
    lonA: GLOBE_NODES[NI[from]].lon,
    latA: GLOBE_NODES[NI[from]].lat,
    lonB: GLOBE_NODES[NI[to]].lon,
    latB: GLOBE_NODES[NI[to]].lat,
  };
}

/** Colores de arco atmosférico (cyan/hielo dominante; pocos en rojo). */
export const ATM_COLORS = {
  ice: { stroke: 'rgba(220, 245, 255, 1)', glow: 'rgba(140, 220, 255, 0.48)', alpha: 0.64 },
  silver: { stroke: 'rgba(180, 215, 235, 1)', glow: 'rgba(130, 185, 215, 0.4)', alpha: 0.52 },
  blue: { stroke: 'rgba(70, 210, 255, 1)', glow: 'rgba(40, 180, 240, 0.45)', alpha: 0.58 },
  red: { stroke: 'rgba(225, 27, 34, 1)', glow: 'rgba(225, 27, 34, 0.28)', alpha: 0.36 },
};

const ATM_BUILT = buildAtmosphericEnvelope(GLOBE_NODES, { seed: 20260723, target: 44 });

/**
 * Arcos atmosféricos desktop 42–50 (generados deterministas).
 * band: low|mid|high — peakAltitude hasta ~0.36.
 */
export const GLOBE_ATMOSPHERIC_ROUTES = ATM_BUILT.routes.map((r) => ({
  ...r,
  a: NI[r.from],
  b: NI[r.to],
}));

export const GLOBE_ATM_SEED = ATM_BUILT.seed;

export const GLOBE_ATM_COUNTS = {
  desktop: GLOBE_ATMOSPHERIC_ROUTES.length,
  tablet: 28,
  mobile: 14,
};

/** Mínimos de tramos atmosféricos visibles simultáneos por viewport. */
export const GLOBE_ATM_VISIBLE_MIN = {
  desktop: 16,
  tablet: 10,
  mobile: 6,
};

export const ATMOSPHERIC_NETWORK_LINKS = GLOBE_ATMOSPHERIC_ROUTES;

/**
 * Paquetes de etiquetas — prioridad igual entre deportes (priority 2).
 * Duraciones variadas; delays escalonados; varias rutas crossesCenter.
 * Gap corto en packetProgress para evitar intervalos vacíos.
 */
export const GLOBE_PACKET_ROUTES = [
  /* —— Deportes (igualdad total) —— */
  {
    id: 'pkt-padbol',
    labelKey: 'padbol',
    category: 'sports',
    route: 'atmospheric',
    ...nodePair('sao', 'mad'),
    peakAltitude: 0.14,
    durationMs: 22000,
    delayMs: 400,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-padel',
    labelKey: 'padel',
    category: 'sports',
    route: 'atmospheric',
    ...nodePair('mad', 'bue'),
    peakAltitude: 0.12,
    durationMs: 22000,
    delayMs: 5800,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-pickleball',
    labelKey: 'pickleball',
    category: 'sports',
    route: 'atmospheric',
    ...nodePair('nyc', 'scl'),
    peakAltitude: 0.14,
    durationMs: 22000,
    delayMs: 11200,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-tennis',
    labelKey: 'tennis',
    category: 'sports',
    route: 'atmospheric',
    ...nodePair('lon', 'tyo'),
    peakAltitude: 0.15,
    durationMs: 22000,
    delayMs: 16600,
    reverse: true,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-padbol-b',
    labelKey: 'padbol',
    category: 'sports',
    route: 'surface',
    ...nodePair('bue', 'mia'),
    peakAltitude: 0.03,
    durationMs: 16000,
    delayMs: 24000,
    reverse: true,
    priority: 3,
  },
  {
    id: 'pkt-padel-b',
    labelKey: 'padel',
    category: 'sports',
    route: 'surface',
    ...nodePair('bcn', 'mex'),
    peakAltitude: 0.03,
    durationMs: 16000,
    delayMs: 29000,
    reverse: false,
    priority: 3,
  },
  {
    id: 'pkt-pickleball-b',
    labelKey: 'pickleball',
    category: 'sports',
    route: 'atmospheric',
    ...nodePair('mad', 'tyo'),
    peakAltitude: 0.15,
    durationMs: 24000,
    delayMs: 28000,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-tennis-b',
    labelKey: 'tennis',
    category: 'sports',
    route: 'atmospheric',
    ...nodePair('mel', 'jnb'),
    peakAltitude: 0.14,
    durationMs: 26000,
    delayMs: 39000,
    reverse: true,
    priority: 3,
    pacific: true,
    crossesCenter: true,
  },

  /* —— Comunidad —— */
  {
    id: 'pkt-community',
    labelKey: 'community',
    category: 'community',
    route: 'surface',
    ...nodePair('del', 'bkk'),
    peakAltitude: 0.03,
    durationMs: 18000,
    delayMs: 1200,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-players',
    labelKey: 'players',
    category: 'community',
    route: 'surface',
    ...nodePair('nyc', 'mad'),
    peakAltitude: 0.04,
    durationMs: 18000,
    delayMs: 0,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-teams',
    labelKey: 'teams',
    category: 'community',
    route: 'atmospheric',
    ...nodePair('chi', 'tyo'),
    peakAltitude: 0.13,
    durationMs: 21000,
    delayMs: 4200,
    reverse: false,
    priority: 2,
    crossesCenter: true,
  },
  {
    id: 'pkt-invitations',
    labelKey: 'invitations',
    category: 'community',
    route: 'surface',
    ...nodePair('par', 'rom'),
    peakAltitude: 0.02,
    durationMs: 14000,
    delayMs: 8600,
    reverse: true,
    priority: 1,
  },
  {
    id: 'pkt-profiles',
    labelKey: 'profiles',
    category: 'community',
    route: 'atmospheric',
    ...nodePair('tor', 'lis'),
    peakAltitude: 0.1,
    durationMs: 19000,
    delayMs: 13200,
    reverse: false,
    priority: 1,
  },
  {
    id: 'pkt-history',
    labelKey: 'history',
    category: 'community',
    route: 'atmospheric',
    ...nodePair('bom', 'cai'),
    peakAltitude: 0.11,
    durationMs: 20000,
    delayMs: 17800,
    reverse: true,
    priority: 1,
  },

  /* —— Competencia —— */
  {
    id: 'pkt-matches',
    labelKey: 'matches',
    category: 'competition',
    route: 'surface',
    ...nodePair('mad', 'ist'),
    peakAltitude: 0.03,
    durationMs: 16000,
    delayMs: 800,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-tournaments',
    labelKey: 'tournaments',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('tyo', 'syd'),
    peakAltitude: 0.12,
    durationMs: 20000,
    delayMs: 4800,
    reverse: true,
    priority: 3,
    pacific: true,
    crossesCenter: true,
  },
  {
    id: 'pkt-competitions',
    labelKey: 'competitions',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('mil', 'tyo'),
    peakAltitude: 0.16,
    durationMs: 28000,
    delayMs: 5400,
    reverse: false,
    priority: 2,
    crossesCenter: true,
  },
  {
    id: 'pkt-standings',
    labelKey: 'standings',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('ber', 'sao'),
    peakAltitude: 0.13,
    durationMs: 23000,
    delayMs: 9800,
    reverse: false,
    priority: 2,
    crossesCenter: true,
  },
  {
    id: 'pkt-live-results',
    labelKey: 'liveResults',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('osa', 'syd'),
    peakAltitude: 0.1,
    durationMs: 18000,
    delayMs: 7800,
    reverse: false,
    priority: 2,
    pacific: true,
  },
  {
    id: 'pkt-stats',
    labelKey: 'stats',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('sel', 'mel'),
    peakAltitude: 0.12,
    durationMs: 17000,
    delayMs: 15200,
    reverse: true,
    priority: 1,
    pacific: true,
  },
  {
    id: 'pkt-ranking',
    labelKey: 'ranking',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('jnb', 'lax'),
    peakAltitude: 0.15,
    durationMs: 24000,
    delayMs: 6200,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-scoreboard',
    labelKey: 'scoreboard',
    category: 'competition',
    route: 'surface',
    ...nodePair('lag', 'nbo'),
    peakAltitude: 0.03,
    durationMs: 18000,
    delayMs: 2000,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-scoreboard-pacific',
    labelKey: 'scoreboard',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('lax', 'syd'),
    peakAltitude: 0.17,
    durationMs: 30000,
    delayMs: 20000,
    reverse: false,
    priority: 2,
    pacific: true,
    crossesCenter: true,
  },
  {
    id: 'pkt-referees',
    labelKey: 'referees',
    category: 'competition',
    route: 'atmospheric',
    ...nodePair('dub', 'mad'),
    peakAltitude: 0.12,
    durationMs: 21000,
    delayMs: 21400,
    reverse: true,
    priority: 1,
  },

  /* —— Gestión —— */
  {
    id: 'pkt-venues',
    labelKey: 'venues',
    category: 'management',
    route: 'surface',
    ...nodePair('bue', 'sao'),
    peakAltitude: 0.02,
    durationMs: 14000,
    delayMs: 2200,
    reverse: true,
    priority: 3,
  },
  {
    id: 'pkt-courts',
    labelKey: 'courts',
    category: 'management',
    route: 'atmospheric',
    ...nodePair('mel', 'bne'),
    peakAltitude: 0.08,
    durationMs: 13000,
    delayMs: 5600,
    reverse: false,
    priority: 1,
    pacific: true,
  },
  {
    id: 'pkt-clubs',
    labelKey: 'clubs',
    category: 'management',
    route: 'surface',
    ...nodePair('lis', 'mad'),
    peakAltitude: 0.025,
    durationMs: 12500,
    delayMs: 12800,
    reverse: true,
    priority: 1,
  },
  {
    id: 'pkt-bookings',
    labelKey: 'bookings',
    category: 'management',
    route: 'surface',
    ...nodePair('mex', 'mia'),
    peakAltitude: 0.03,
    durationMs: 13000,
    delayMs: 7600,
    reverse: true,
    priority: 1,
  },
  {
    id: 'pkt-calendar',
    labelKey: 'calendar',
    category: 'management',
    route: 'surface',
    ...nodePair('ams', 'war'),
    peakAltitude: 0.02,
    durationMs: 12000,
    delayMs: 10200,
    reverse: false,
    priority: 1,
  },
  {
    id: 'pkt-registrations',
    labelKey: 'registrations',
    category: 'management',
    route: 'surface',
    ...nodePair('bcn', 'par'),
    peakAltitude: 0.02,
    durationMs: 11500,
    delayMs: 14600,
    reverse: true,
    priority: 1,
  },
  {
    id: 'pkt-organizations',
    labelKey: 'organizations',
    category: 'management',
    route: 'atmospheric',
    ...nodePair('cai', 'syd'),
    peakAltitude: 0.14,
    durationMs: 22000,
    delayMs: 14200,
    reverse: false,
    priority: 1,
    crossesCenter: true,
  },
  {
    id: 'pkt-associations',
    labelKey: 'associations',
    category: 'management',
    route: 'atmospheric',
    ...nodePair('bue', 'mad'),
    peakAltitude: 0.14,
    durationMs: 24000,
    delayMs: 3000,
    reverse: false,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-federations',
    labelKey: 'federations',
    category: 'management',
    route: 'atmospheric',
    ...nodePair('nyc', 'tyo'),
    peakAltitude: 0.16,
    durationMs: 26000,
    delayMs: 9000,
    reverse: true,
    priority: 3,
    crossesCenter: true,
  },
  {
    id: 'pkt-academies',
    labelKey: 'academies',
    category: 'management',
    route: 'surface',
    ...nodePair('rio', 'scl'),
    peakAltitude: 0.03,
    durationMs: 14000,
    delayMs: 11800,
    reverse: false,
    priority: 1,
  },
  {
    id: 'pkt-coaches',
    labelKey: 'coaches',
    category: 'management',
    route: 'surface',
    ...nodePair('mia', 'nyc'),
    peakAltitude: 0.025,
    durationMs: 12000,
    delayMs: 16400,
    reverse: true,
    priority: 1,
  },

  /* —— Experiencia —— */
  {
    id: 'pkt-padcoins',
    labelKey: 'padcoins',
    category: 'experience',
    route: 'atmospheric',
    ...nodePair('sgp', 'syd'),
    peakAltitude: 0.11,
    durationMs: 18000,
    delayMs: 9100,
    reverse: false,
    priority: 1,
    pacific: true,
  },
  {
    id: 'pkt-memberships',
    labelKey: 'memberships',
    category: 'experience',
    route: 'surface',
    ...nodePair('lon', 'par'),
    peakAltitude: 0.02,
    durationMs: 12000,
    delayMs: 10500,
    reverse: false,
    priority: 1,
  },
  {
    id: 'pkt-loyalty',
    labelKey: 'loyalty',
    category: 'experience',
    route: 'atmospheric',
    ...nodePair('sfo', 'akl'),
    peakAltitude: 0.15,
    durationMs: 23000,
    delayMs: 15800,
    reverse: false,
    priority: 1,
    pacific: true,
    crossesCenter: true,
  },
  {
    id: 'pkt-benefits',
    labelKey: 'benefits',
    category: 'experience',
    route: 'atmospheric',
    ...nodePair('auh', 'sgp'),
    peakAltitude: 0.12,
    durationMs: 20000,
    delayMs: 18800,
    reverse: false,
    priority: 1,
  },
  {
    id: 'pkt-awards',
    labelKey: 'awards',
    category: 'experience',
    route: 'atmospheric',
    ...nodePair('cpt', 'dub'),
    peakAltitude: 0.13,
    durationMs: 22000,
    delayMs: 22600,
    reverse: true,
    priority: 1,
  },
  {
    id: 'pkt-events',
    labelKey: 'events',
    category: 'experience',
    route: 'atmospheric',
    ...nodePair('bne', 'lax'),
    peakAltitude: 0.16,
    durationMs: 25000,
    delayMs: 13400,
    reverse: true,
    priority: 1,
    pacific: true,
    crossesCenter: true,
  },
  {
    id: 'pkt-notifications',
    labelKey: 'notifications',
    category: 'experience',
    route: 'atmospheric',
    ...nodePair('ber', 'bog'),
    peakAltitude: 0.12,
    durationMs: 19000,
    delayMs: 17200,
    reverse: false,
    priority: 1,
    crossesCenter: true,
  },
  {
    id: 'pkt-experiences',
    labelKey: 'experiences',
    category: 'experience',
    route: 'atmospheric',
    ...nodePair('jkt', 'scl'),
    peakAltitude: 0.17,
    durationMs: 27000,
    delayMs: 6700,
    reverse: true,
    priority: 1,
    pacific: true,
    crossesCenter: true,
  },
];

export const GLOBE_STATIC_PACKETS = GLOBE_STATIC_LABELS.desktop;

export function altitudeAt(t, peak) {
  const x = Math.max(0, Math.min(1, t));
  return peak * Math.sin(Math.PI * x);
}

export function easeInOutCubic(t) {
  const x = Math.max(0, Math.min(1, t));
  return x < 0.5 ? 4 * x * x * x : 1 - ((-2 * x + 2) ** 3) / 2;
}

/** Gap corto: superposición temporal y menos ventanas vacías. */
export const PACKET_CYCLE_GAP_MS = 900;

export function packetProgress(elapsedMs, route) {
  const gap = PACKET_CYCLE_GAP_MS;
  const cycle = route.durationMs + gap;
  const local = ((elapsedMs - route.delayMs) % cycle + cycle) % cycle;
  if (local > route.durationMs) return null;
  const raw = local / route.durationMs;
  const t = route.reverse ? 1 - easeInOutCubic(raw) : easeInOutCubic(raw);
  const edge = Math.min(local / 1100, (route.durationMs - local) / 1100, 1);
  return { t, edge, local };
}
