import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const { Client } = pg;
const here = path.dirname(fileURLToPath(import.meta.url));
const backendRoot = path.resolve(here, '..');
const TEST_DATABASE = 'padbol_whatsapp_test';
const LOCAL_HOSTS = new Set(['127.0.0.1', 'localhost', '::1']);

const adminUrlText = String(process.env.WHATSAPP_LOCAL_DB_ADMIN_URL || '').trim();
if (!adminUrlText) {
  throw new Error('Falta WHATSAPP_LOCAL_DB_ADMIN_URL para la base postgres local.');
}
const adminUrl = new URL(adminUrlText);
if (!['postgres:', 'postgresql:'].includes(adminUrl.protocol) || !LOCAL_HOSTS.has(adminUrl.hostname)) {
  throw new Error('El harness WhatsApp sólo admite PostgreSQL local.');
}
if (adminUrl.pathname !== '/postgres') {
  throw new Error('WHATSAPP_LOCAL_DB_ADMIN_URL debe apuntar a la base local postgres.');
}

const testUrl = new URL(adminUrl);
testUrl.pathname = `/${TEST_DATABASE}`;
const multisedeSql = fs.readFileSync(
  path.resolve(backendRoot, 'sql/20260904150000_multisede_organizations.sql'),
  'utf8',
);
const whatsappSql = fs.readFileSync(
  path.resolve(backendRoot, 'sql/20260909173000_whatsapp_cloud_core.sql'),
  'utf8',
);

async function expectSqlState(client, sql, params, expectedState) {
  await assert.rejects(
    client.query(sql, params),
    (error) => error?.code === expectedState,
  );
}

async function expectRoleDenied(client, role, sql, params = []) {
  await client.query('begin');
  try {
    await client.query(`set local role ${role}`);
    await expectSqlState(client, sql, params, '42501');
  } finally {
    await client.query('rollback');
  }
}

async function check(name, work) {
  await work();
  console.log(`ok - ${name}`);
}

const admin = new Client({ connectionString: adminUrl.toString() });
let database = null;
let adminConnected = false;

try {
  await admin.connect();
  adminConnected = true;
  await admin.query(`drop database if exists ${TEST_DATABASE} with (force)`);
  await admin.query(`create database ${TEST_DATABASE} template template0`);

  database = new Client({ connectionString: testUrl.toString() });
  await database.connect();
  await database.query('create extension if not exists pgcrypto');
  await database.query(`
    create table public.sedes (
      id bigint primary key,
      nombre text not null
    );
    create table public.user_roles (
      id bigint generated by default as identity primary key,
      role text,
      alcance text
    );
    create table public.invitaciones_admin (
      id bigint generated by default as identity primary key
    );
    create table public.sedes_pendientes (
      id bigint generated by default as identity primary key
    );
  `);
  await database.query(multisedeSql);
  await database.query(whatsappSql);

  await database.query(`
    insert into public.sedes (id, nombre)
    values (101, 'Fixture sede A'), (202, 'Fixture sede B');
  `);
  const organizations = await database.query(`
    insert into public.organizaciones (nombre, estado)
    values ('Fixture organización A', 'activa'), ('Fixture organización B', 'activa')
    returning id, nombre;
  `);
  const organizationA = organizations.rows.find((row) => row.nombre.endsWith('A')).id;
  const organizationB = organizations.rows.find((row) => row.nombre.endsWith('B')).id;
  await database.query(`
    insert into public.organizacion_sedes (organizacion_id, sede_id)
    values ($1, 101), ($2, 202);
  `, [organizationA, organizationB]);

  const tenantAResult = await database.query(`
    insert into public.whatsapp_tenants (organization_id, display_name, status)
    values ($1, 'Fixture tenant A', 'active') returning id;
  `, [organizationA]);
  const tenantBResult = await database.query(`
    insert into public.whatsapp_tenants (sede_id, display_name, status)
    values (202, 'Fixture tenant B', 'active') returning id;
  `);
  const tenantA = tenantAResult.rows[0].id;
  const tenantB = tenantBResult.rows[0].id;
  const channelAResult = await database.query(`
    insert into public.whatsapp_tenant_channels
      (tenant_id, meta_phone_number_id, credential_ref, active)
    values ($1, '111111111111111', 'TEST_A', true) returning id;
  `, [tenantA]);
  const channelBResult = await database.query(`
    insert into public.whatsapp_tenant_channels
      (tenant_id, meta_phone_number_id, credential_ref, active)
    values ($1, '222222222222222', 'TEST_B', true) returning id;
  `, [tenantB]);
  const channelA = channelAResult.rows[0].id;
  const channelB = channelBResult.rows[0].id;

  await check('el scope tenant exige exactamente organización o sede', async () => {
    await expectSqlState(database, `
      insert into public.whatsapp_tenants (display_name, status)
      values ('Sin scope', 'active');
    `, [], '23514');
    await expectSqlState(database, `
      insert into public.whatsapp_tenants (organization_id, sede_id, display_name, status)
      values ($1, 101, 'Scope doble', 'active');
    `, [organizationA], '23514');
  });

  await check('un canal de otro tenant no puede recibir su mensaje', async () => {
    await expectSqlState(database, `
      insert into public.whatsapp_inbound_messages
        (tenant_id, channel_id, provider_message_id, from_wa_id, message_type, text_body, received_at)
      values ($1, $2, 'wamid.cross-channel', '15550000001', 'text', 'No debe entrar', now());
    `, [tenantA, channelB], '23503');
  });

  const inboundAResult = await database.query(`
    insert into public.whatsapp_inbound_messages
      (tenant_id, channel_id, provider_message_id, from_wa_id, message_type, text_body, received_at)
    values ($1, $2, 'wamid.shared-provider', '15550000001', 'text', 'Mensaje A', now())
    returning id;
  `, [tenantA, channelA]);
  const inboundBResult = await database.query(`
    insert into public.whatsapp_inbound_messages
      (tenant_id, channel_id, provider_message_id, from_wa_id, message_type, text_body, received_at)
    values ($1, $2, 'wamid.shared-provider', '15550000002', 'text', 'Mensaje B', now())
    returning id;
  `, [tenantB, channelB]);
  const inboundA = inboundAResult.rows[0].id;
  const inboundB = inboundBResult.rows[0].id;

  await check('message id es idempotente dentro del tenant y reutilizable entre tenants', async () => {
    await expectSqlState(database, `
      insert into public.whatsapp_inbound_messages
        (tenant_id, channel_id, provider_message_id, from_wa_id, message_type, text_body, received_at)
      values ($1, $2, 'wamid.shared-provider', '15550000003', 'text', 'Duplicado A', now());
    `, [tenantA, channelA], '23505');
    const counts = await database.query(`
      select tenant_id, count(*)::int as total
      from public.whatsapp_inbound_messages
      where provider_message_id = 'wamid.shared-provider'
      group by tenant_id order by tenant_id;
    `);
    assert.equal(counts.rows.length, 2);
    assert.deepEqual(counts.rows.map((row) => row.total), [1, 1]);
  });

  await check('una outbox no puede cruzar tenant, canal o mensaje entrante', async () => {
    await expectSqlState(database, `
      insert into public.whatsapp_outbox
        (tenant_id, channel_id, inbound_message_id, idempotency_key, to_wa_id,
         reply_to_provider_message_id, text_body, customer_service_window_expires_at)
      values ($1, $2, $3, 'cross-outbox-channel', '15550000001',
              'wamid.shared-provider', 'No debe salir', now() + interval '24 hours');
    `, [tenantA, channelB, inboundA], '23503');
    await expectSqlState(database, `
      insert into public.whatsapp_outbox
        (tenant_id, channel_id, inbound_message_id, idempotency_key, to_wa_id,
         reply_to_provider_message_id, text_body, customer_service_window_expires_at)
      values ($1, $2, $3, 'cross-outbox-inbound', '15550000002',
              'wamid.shared-provider', 'No debe salir', now() + interval '24 hours');
    `, [tenantA, channelA, inboundB], '23503');
  });

  const outboxAResult = await database.query(`
    insert into public.whatsapp_outbox
      (tenant_id, channel_id, inbound_message_id, idempotency_key, to_wa_id,
       reply_to_provider_message_id, text_body, customer_service_window_expires_at)
    values ($1, $2, $3, 'same-idempotency-key', '15550000001',
            'wamid.shared-provider', 'Respuesta A', now() + interval '24 hours')
    returning id;
  `, [tenantA, channelA, inboundA]);
  const outboxA = outboxAResult.rows[0].id;
  await database.query(`
    insert into public.whatsapp_outbox
      (tenant_id, channel_id, inbound_message_id, idempotency_key, to_wa_id,
       reply_to_provider_message_id, text_body, customer_service_window_expires_at)
    values ($1, $2, $3, 'same-idempotency-key', '15550000002',
            'wamid.shared-provider', 'Respuesta B', now() + interval '24 hours');
  `, [tenantB, channelB, inboundB]);

  await check('idempotency key es única sólo dentro de cada tenant', async () => {
    await expectSqlState(database, `
      insert into public.whatsapp_outbox
        (tenant_id, channel_id, inbound_message_id, idempotency_key, to_wa_id,
         reply_to_provider_message_id, text_body, customer_service_window_expires_at)
      values ($1, $2, $3, 'same-idempotency-key', '15550000001',
              'wamid.shared-provider', 'Duplicado A', now() + interval '24 hours');
    `, [tenantA, channelA, inboundA], '23505');
    const count = await database.query(`
      select count(*)::int as total from public.whatsapp_outbox
      where idempotency_key = 'same-idempotency-key';
    `);
    assert.equal(count.rows[0].total, 2);
  });

  await check('anon y authenticated no pueden leer ni mutar WhatsApp', async () => {
    for (const role of ['anon', 'authenticated']) {
      await expectRoleDenied(database, role, 'select * from public.whatsapp_inbound_messages limit 1');
      await expectRoleDenied(database, role, `
        insert into public.whatsapp_inbound_messages
          (tenant_id, channel_id, provider_message_id, from_wa_id, message_type, text_body, received_at)
        values ($1, $2, 'wamid.forbidden', '15550000004', 'text', 'No', now());
      `, [tenantA, channelA]);
      await expectRoleDenied(database, role, `
        update public.whatsapp_outbox set status = 'cancelled' where tenant_id = $1;
      `, [tenantA]);
      await expectRoleDenied(database, role, `
        delete from public.whatsapp_inbound_messages where tenant_id = $1;
      `, [tenantA]);
    }
  });

  await check('service_role puede operar mediante el backend', async () => {
    await database.query('begin');
    try {
      await database.query('set local role service_role');
      const inserted = await database.query(`
        insert into public.whatsapp_inbound_messages
          (tenant_id, channel_id, provider_message_id, from_wa_id, message_type, text_body, received_at)
        values ($1, $2, 'wamid.service-role', '15550000005', 'text', 'Servicio', now())
        returning id;
      `, [tenantA, channelA]);
      const updated = await database.query(`
        update public.whatsapp_inbound_messages set text_body = 'Servicio actualizado'
        where tenant_id = $1 and id = $2 returning id;
      `, [tenantA, inserted.rows[0].id]);
      assert.equal(updated.rowCount, 1);
      const deleted = await database.query(`
        delete from public.whatsapp_inbound_messages
        where tenant_id = $1 and id = $2 returning id;
      `, [tenantA, inserted.rows[0].id]);
      assert.equal(deleted.rowCount, 1);
    } finally {
      await database.query('rollback');
    }
  });

  await check('RLS queda habilitado en las cuatro tablas', async () => {
    const result = await database.query(`
      select relname, relrowsecurity
      from pg_class
      where relnamespace = 'public'::regnamespace
        and relname in (
          'whatsapp_tenants', 'whatsapp_tenant_channels',
          'whatsapp_inbound_messages', 'whatsapp_outbox'
        )
      order by relname;
    `);
    assert.equal(result.rows.length, 4);
    assert.equal(result.rows.every((row) => row.relrowsecurity === true), true);
  });

  await check('dos claims concurrentes reclaman exactamente una salida', async () => {
    const claimantA = new Client({ connectionString: testUrl.toString() });
    const claimantB = new Client({ connectionString: testUrl.toString() });
    await Promise.all([claimantA.connect(), claimantB.connect()]);
    try {
      const claimSql = `
        update public.whatsapp_outbox
        set status = 'sending', attempts = attempts + 1, last_attempt_at = now()
        where tenant_id = $1 and id = $2 and status = 'pending'
        returning id;
      `;
      const [claimA, claimB] = await Promise.all([
        claimantA.query(claimSql, [tenantA, outboxA]),
        claimantB.query(claimSql, [tenantA, outboxA]),
      ]);
      assert.equal(claimA.rowCount + claimB.rowCount, 1);
      const final = await database.query(`
        select status, attempts from public.whatsapp_outbox
        where tenant_id = $1 and id = $2;
      `, [tenantA, outboxA]);
      assert.deepEqual(final.rows[0], { status: 'sending', attempts: 1 });
    } finally {
      await Promise.all([claimantA.end(), claimantB.end()]);
    }
  });

  await check('canal inactivo y tenant pausado quedan fuera del lookup operativo', async () => {
    await database.query(`
      update public.whatsapp_tenant_channels set active = false
      where tenant_id = $1 and id = $2;
    `, [tenantA, channelA]);
    let lookup = await database.query(`
      select c.id from public.whatsapp_tenant_channels c
      join public.whatsapp_tenants t on t.id = c.tenant_id
      where c.meta_phone_number_id = '111111111111111'
        and c.active = true and t.status = 'active';
    `);
    assert.equal(lookup.rowCount, 0);
    await database.query(`
      update public.whatsapp_tenant_channels set active = true
      where tenant_id = $1 and id = $2;
    `, [tenantA, channelA]);
    await database.query(`
      update public.whatsapp_tenants set status = 'paused' where id = $1;
    `, [tenantA]);
    lookup = await database.query(`
      select c.id from public.whatsapp_tenant_channels c
      join public.whatsapp_tenants t on t.id = c.tenant_id
      where c.meta_phone_number_id = '111111111111111'
        and c.active = true and t.status = 'active';
    `);
    assert.equal(lookup.rowCount, 0);
  });

  console.log('1..10');
} finally {
  if (database) await database.end().catch(() => {});
  if (adminConnected) {
    await admin.query(`drop database if exists ${TEST_DATABASE} with (force)`).catch(() => {});
    await admin.end().catch(() => {});
  }
}
