import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const { Client } = pg;
const here = path.dirname(fileURLToPath(import.meta.url));
const backendRoot = path.resolve(here, '..');
const TEST_DATABASE = 'padbol_whatsapp_assistant_test';
const LOCAL_HOSTS = new Set(['127.0.0.1', 'localhost', '::1']);

const adminUrlText = String(process.env.WHATSAPP_LOCAL_DB_ADMIN_URL || '').trim();
if (!adminUrlText) {
  throw new Error('Falta WHATSAPP_LOCAL_DB_ADMIN_URL para la base postgres local.');
}
const adminUrl = new URL(adminUrlText);
if (!['postgres:', 'postgresql:'].includes(adminUrl.protocol) || !LOCAL_HOSTS.has(adminUrl.hostname)) {
  throw new Error('El harness del asistente sólo admite PostgreSQL local.');
}
if (adminUrl.pathname !== '/postgres') {
  throw new Error('WHATSAPP_LOCAL_DB_ADMIN_URL debe apuntar a la base local postgres.');
}

const testUrl = new URL(adminUrl);
testUrl.pathname = `/${TEST_DATABASE}`;

const multisedeSql = fs.readFileSync(
  path.resolve(backendRoot, 'sql/20260904150000_multisede_organizations.sql'), 'utf8');
const coreSql = fs.readFileSync(
  path.resolve(backendRoot, 'sql/20260909173000_whatsapp_cloud_core.sql'), 'utf8');
const assistantSql = fs.readFileSync(
  path.resolve(backendRoot, 'sql/20260914000000_whatsapp_assistant_knowledge.sql'), 'utf8');

const admin = new Client({ connectionString: adminUrl.toString() });
let database = null;
let adminConnected = false;

async function expectRoleDenied(client, role, sql, params = []) {
  await client.query('begin');
  try {
    await client.query(`set local role ${role}`);
    await assert.rejects(client.query(sql, params), (e) => e?.code === '42501');
  } finally {
    await client.query('rollback');
  }
}

try {
  await admin.connect();
  adminConnected = true;
  await admin.query(`drop database if exists ${TEST_DATABASE} with (force)`);
  await admin.query(`create database ${TEST_DATABASE} template template0`);

  database = new Client({ connectionString: testUrl.toString() });
  await database.connect();
  await database.query('create extension if not exists pgcrypto');
  await database.query(`
    do $$
    begin
      if not exists (select from pg_roles where rolname = 'anon') then create role anon; end if;
      if not exists (select from pg_roles where rolname = 'authenticated') then create role authenticated; end if;
      if not exists (select from pg_roles where rolname = 'service_role') then create role service_role bypassrls; end if;
    end
    $$;
  `);
  await database.query(`
    create table public.sedes (
      id bigint primary key,
      nombre text not null
    );
    create table public.user_roles (
      id bigint generated by default as identity primary key,
      role text,
      alcance text
    );
    create table public.invitaciones_admin (
      id bigint generated by default as identity primary key
    );
    create table public.sedes_pendientes (
      id bigint generated by default as identity primary key
    );
  `);
  await database.query(multisedeSql);
  await database.query(coreSql);
  await database.query(assistantSql);

  const tables = (await database.query(`
    select tablename from pg_tables where schemaname = 'public'
      and tablename in (
        'whatsapp_assistant_config', 'whatsapp_assistant_topics',
        'whatsapp_assistant_responses', 'whatsapp_assistant_operators',
        'whatsapp_assistant_classifications'
      ) order by tablename;
  `)).rows.map((r) => r.tablename);
  assert.deepEqual(tables, [
    'whatsapp_assistant_classifications',
    'whatsapp_assistant_config',
    'whatsapp_assistant_operators',
    'whatsapp_assistant_responses',
    'whatsapp_assistant_topics',
  ]);
  console.log('ok - tablas del asistente creadas');

  const rls = (await database.query(`
    select relname, relrowsecurity from pg_class
    where relnamespace = 'public'::regnamespace
      and relkind = 'r'
      and relname like 'whatsapp_assistant_%' order by relname;
  `)).rows;
  assert.equal(rls.length, 5);
  assert.equal(rls.every((r) => r.relrowsecurity === true), true);
  console.log('ok - RLS habilitado en las cinco tablas del asistente');

  await expectRoleDenied(database, 'anon', 'select * from public.whatsapp_assistant_config limit 1');
  await expectRoleDenied(database, 'authenticated', 'select * from public.whatsapp_assistant_responses limit 1');
  console.log('ok - anon/authenticated sin acceso');

  await database.query('begin');
  try {
    await database.query('set local role service_role');
    await database.query(`
      insert into public.whatsapp_assistant_config (key, value)
      values ('academy_url', 'https://padbol.com'), ('dispatch_allowed', 'false');
    `);
    await database.query(`
      insert into public.whatsapp_assistant_topics (slug, title_es, title_en, priority)
      values ('courses_academy', 'Cursos', 'Courses', 1);
    `);
    await database.query(`
      insert into public.whatsapp_assistant_responses (topic_slug, locale, body)
      values ('courses_academy', 'es', 'Respuesta segura sin precios.');
    `);
    await database.query(`
      insert into public.whatsapp_assistant_operators (display_name, external_id)
      values ('Operador A', 'operador-a@padbol.com');
    `);
    await assert.rejects(
      database.query(`
        insert into public.whatsapp_assistant_config (key, value)
        values ('CLAVE_INVALIDA CON ESPACIOS', 'x');
      `),
      (e) => e?.code === '23514',
    );
  } finally {
    await database.query('rollback');
  }
  console.log('ok - service_role opera y las restricciones rechazan claves inválidas');

  console.log('1..4');
} finally {
  if (database) await database.end().catch(() => {});
  if (adminConnected) {
    await admin.query(`drop database if exists ${TEST_DATABASE} with (force)`).catch(() => {});
    await admin.end().catch(() => {});
  }
}
