const ES = {
  metaTitle: 'Padbol Match para clubes — Planes',
  metaDescription: 'Padbol Match reúne reservas, jugadores, partidos, torneos, rankings, marcador digital y gestión de clubes multideporte.',
  notDefined: 'A definir', featured: 'MÁS ELEGIDO', perMonth: '/ mes', or: 'o', perYear: '/ año', limits: 'Límites del plan', venueService: 'Servicio a la sede', commissionNote: 'sobre operaciones procesadas mediante Padbol Match',
  draft: 'BORRADOR INTERNO · NO PUBLICADO', back: '← Para administradores', eyebrow: 'PADBOL MATCH PARA CLUBES', title: 'Todo tu club.', titleAccent: 'Una sola plataforma.', sports: 'Padbol · Padel · Pickleball · Tenis', lead: 'Reservas, jugadores, partidos, torneos, rankings, marcador en vivo, membresías y gestión desde un mismo lugar.', start: 'EMPEZAR SIN ABONO', seePlans: 'VER PLANES', operationAria: 'Operación conectada del club', liveClub: 'CLUB EN VIVO', fourSports: '4 deportes', bookings: 'Reservas y disponibilidad', liveMatch: 'Partido y marcador en vivo', results: 'Resultados, ranking y retorno', connected: 'Una operación conectada antes, durante y después de jugar.',
  playerFeeAria: 'Comisiones al jugador', playerFeeTitle: 'EL JUGADOR PAGA 0% DE COMISIÓN A PADBOL MATCH.', playerFeeText: 'Las comisiones de los planes corresponden al servicio prestado a la sede. Los costos de Mercado Pago, Stripe u otro procesador son independientes.',
  padbolBenefit: 'BENEFICIO EXCLUSIVO PARA SEDES PADBOL', padbolOwnerTitle: '¿Sos propietario de una o más Padbol Courts?', padbolOwnerText: 'Solicitá Padbol Match Pro sin cargo durante 12 meses y administrá tu sede desde una sola plataforma.', padbolOwnerHint: 'Contanos sobre tu sede. Nuestro equipo te contactará para evaluar la solicitud y los próximos pasos.', padbolOwnerCta: 'SOLICITAR 12 MESES PRO',
  plansEyebrow: 'PLANES PARA CRECER A TU RITMO', plansTitle: 'Empezá administrando.', plansAccent: 'Pasá a Pro para automatizar.', finePrint: 'Los límites, precios, promociones y comisiones dependen de la región y de la configuración vigente. Business se define por contacto comercial y validación técnica.',
  scoreboardEyebrow: 'TU MARCADOR DIGITAL, INCLUIDO DESDE STARTER', scoreboardTitle: 'El partido en vivo.', scoreboardAccent: 'Sin equipamiento específico.', devices: 'Teléfono · Tablet · Computadora · TV', scoreboardItems: ['Score y actualización en vivo.', 'Visualización en pantalla o TV.', 'Uso inalámbrico desde los dispositivos del club.'], scoreboardNote: 'Pro suma sponsors propios, torneos automatizados, reportes exportables, campañas PadCoins y notificaciones segmentadas.', scoreboardAria: 'Marcador digital de Padbol Match durante un partido', scoreboardCaption: 'Marcador actualmente disponible en Padbol Match.',
  multisportEyebrow: 'UN CLUB. CUATRO DEPORTES.', multisportTitle: 'Padbol · Padel · Pickleball · Tenis', multisportText: 'Administrá todas tus Padbol Courts y demás canchas desde una misma plataforma, aunque tu club practique diferentes deportes.',
  automationEyebrow: 'STARTER ADMINISTRA. PRO AUTOMATIZA.', automationTitle: 'Más movimiento para tu club.', automationAccent: 'Menos tareas repetidas.', automation: [
    ['Torneos automáticos', 'Sorteo → zonas → partidos → resultados → clasificación → cruces → finales.'],
    ['Generá nuevos ingresos', 'Membresías, promociones y espacios propios para sponsors.'],
    ['Fidelizá jugadores', 'PadCoins, campañas y beneficios configurados por el club.'],
    ['Reducí el costo de plataforma', 'Starter: 1% · Pro: 0,65%. Valores administrables por región.'],
  ],
  migrationEyebrow: '¿YA USÁS OTRO SISTEMA?', migrationTitle: 'No empezás de cero.', migrationText: 'Podemos importar información que pertenezca legítimamente a la sede y que tenga un formato compatible. El alcance se valida antes de comenzar.', migration: [['Starter', 'Importación de archivos compatibles, sujeta a validación.'], ['Pro', 'Migración asistida.'], ['Business', 'Migración personalizada.']],
  growthAria: 'Herramientas de crecimiento Pro', membershipTitle: 'CREÁ TU PROPIA MEMBRESÍA', membershipText: 'Definí precio, duración, beneficios, descuentos, horarios, prioridad, reservas incluidas y PadCoins. Es una membresía propia del club, separada de cualquier futura membresía global del jugador.', screensTitle: 'CONVERTÍ TUS PANTALLAS EN UN ACTIVO', screensText: 'Gestioná sponsors propios en marcador, TV, torneos y espacios locales disponibles. El inventario de la sede se mantiene separado del inventario Global Padbol Match y del de FIPA.',
  experiencesEyebrow: 'CINCO EXPERIENCIAS. UN SOLO PRODUCTO.', experiencesText: 'Son interfaces visuales de Padbol Match. No son planes comerciales y no determinan si un club usa Starter, Pro o Business.', finalTitle: 'Empezá sin costo fijo.', finalAccent: 'La operación sigue siendo tuya.', talk: 'HABLEMOS',
  plans: {
    starter: { courtsLabel: 'Hasta 4 canchas', adminsLabel: '1 administrador', summary: 'Para clubes de hasta 4 canchas que quieren administrar su operación sin abono mensual.', ctaLabel: 'EMPEZAR SIN ABONO', features: ['Padbol, Padel, Pickleball y Tenis', 'Jugadores y clientes ilimitados', 'Perfil público de la sede, canchas, horarios, tarifas y disponibilidad', 'Reservas online y carga manual de reservas', 'Partidos, carga de resultados y ranking del club', 'Torneos administrados por la sede: inscripciones, equipos, partidos y resultados', 'Marcador digital con control en vivo y salida para pantalla o TV', 'Panel operativo de reservas, ocupación e ingresos', 'Consulta de saldos, movimientos y canjes de PadCoins de la sede', 'Importación de archivos compatibles, sujeta a validación previa'] },
    pro: { courtsLabel: 'Hasta 12 canchas', adminsLabel: 'Hasta 5 administradores', summary: 'Para clubes que quieren automatizar la operación y hacer crecer su comunidad.', ctaLabel: 'ELEGIR PRO', features: ['Todo lo incluido en Starter', 'Torneos automatizados: sorteos, zonas, fixture, clasificación, llaves y podios', 'Reportes y exportaciones de reservas, ingresos y PadCoins', 'Listas de espera de torneos y avisos de apertura', 'Creación de campañas, promociones, premios y canjes con PadCoins', 'Membresías propias del club', 'Sponsors propios en marcador, torneos y pantallas de la sede', 'Notificaciones segmentadas a jugadores de la sede', 'Migración asistida y soporte prioritario'] },
    business: { pricePrefix: 'Desde', commissionPrefix: 'Desde', courtsLabel: '13+ canchas', adminsLabel: 'Condiciones personalizadas', summary: 'Soluciones multisede y personalizadas para cadenas, operadores y licenciatarios.', ctaLabel: 'HABLEMOS', features: ['Todo lo incluido en Pro', 'Alcance multisede definido con cada organización', 'Permisos y administración centralizada según proyecto', 'Reportes consolidados y campañas de red según alcance', 'Migración personalizada', 'Integraciones y API sujetas a validación técnica', 'Soporte dedicado'] },
  },
};

const EN = {
  ...ES,
  metaTitle: 'Padbol Match for clubs — Plans', metaDescription: 'Padbol Match brings bookings, players, matches, tournaments, rankings, digital scoreboard and multisport club management together.',
  notDefined: 'To be defined', featured: 'MOST POPULAR', perMonth: '/ month', or: 'or', perYear: '/ year', limits: 'Plan limits', venueService: 'Service for the club', commissionNote: 'on transactions processed through Padbol Match',
  draft: 'INTERNAL DRAFT · NOT PUBLISHED', back: '← For administrators', eyebrow: 'PADBOL MATCH FOR CLUBS', title: 'Your entire club.', titleAccent: 'One platform.', sports: 'Padbol · Padel · Pickleball · Tennis', lead: 'Bookings, players, matches, tournaments, rankings, live scoreboard, memberships and management in one place.', start: 'START WITHOUT A SUBSCRIPTION', seePlans: 'VIEW PLANS', operationAria: 'Connected club operation', liveClub: 'CLUB LIVE', fourSports: '4 sports', bookings: 'Bookings and availability', liveMatch: 'Live match and scoreboard', results: 'Results, ranking and return visits', connected: 'One connected operation before, during and after play.',
  playerFeeAria: 'Player fees', playerFeeTitle: 'PLAYERS PAY 0% COMMISSION TO PADBOL MATCH.', playerFeeText: 'Plan commissions correspond to the service provided to the club. Mercado Pago, Stripe or other payment processor costs are separate.',
  padbolBenefit: 'EXCLUSIVE BENEFIT FOR PADBOL CLUBS', padbolOwnerTitle: 'Do you own one or more Padbol Courts?', padbolOwnerText: 'Apply for Padbol Match Pro free for 12 months and manage your club from one platform.', padbolOwnerHint: 'Tell us about your club. Our team will contact you to review the application and next steps.', padbolOwnerCta: 'APPLY FOR 12 MONTHS OF PRO',
  plansEyebrow: 'PLANS THAT GROW WITH YOU', plansTitle: 'Start by managing.', plansAccent: 'Move to Pro to automate.', finePrint: 'Limits, prices, promotions and commissions depend on the region and current configuration. Business terms are defined through commercial contact and technical validation.',
  scoreboardEyebrow: 'YOUR DIGITAL SCOREBOARD, INCLUDED FROM STARTER', scoreboardTitle: 'The match live.', scoreboardAccent: 'No special equipment.', devices: 'Phone · Tablet · Computer · TV', scoreboardItems: ['Live scoring and updates.', 'Display on a screen or TV.', 'Wireless control from club devices.'], scoreboardNote: 'Pro adds your own sponsors, automated tournaments, exportable reports, PadCoins campaigns and segmented notifications.', scoreboardAria: 'Padbol Match digital scoreboard during a match', scoreboardCaption: 'Scoreboard currently available in Padbol Match.',
  multisportEyebrow: 'ONE CLUB. FOUR SPORTS.', multisportTitle: 'Padbol · Padel · Pickleball · Tennis', multisportText: 'Manage every Padbol Court and other playing court from the same platform, even when your club offers different sports.',
  automationEyebrow: 'STARTER MANAGES. PRO AUTOMATES.', automationTitle: 'More activity for your club.', automationAccent: 'Fewer repetitive tasks.', automation: [['Automated tournaments', 'Draw → groups → matches → results → standings → brackets → finals.'], ['Create new revenue', 'Memberships, promotions and your own sponsor placements.'], ['Build player loyalty', 'PadCoins, campaigns and benefits configured by the club.'], ['Reduce platform cost', 'Starter: 1% · Pro: 0.65%. Values can be managed by region.']],
  migrationEyebrow: 'ALREADY USING ANOTHER SYSTEM?', migrationTitle: 'You do not start from zero.', migrationText: 'We can import information that legitimately belongs to the club and uses a compatible format. Scope is validated before work begins.', migration: [['Starter', 'Compatible file import, subject to validation.'], ['Pro', 'Assisted migration.'], ['Business', 'Custom migration.']],
  growthAria: 'Pro growth tools', membershipTitle: 'CREATE YOUR OWN MEMBERSHIP', membershipText: 'Define price, duration, benefits, discounts, schedules, priority, included bookings and PadCoins. This is the club’s own membership, separate from any future global player membership.', screensTitle: 'TURN YOUR SCREENS INTO AN ASSET', screensText: 'Manage your own sponsors on the scoreboard, TV, tournaments and available local placements. Club inventory remains separate from Global Padbol Match and FIPA inventory.',
  experiencesEyebrow: 'FIVE EXPERIENCES. ONE PRODUCT.', experiencesText: 'These are Padbol Match visual interfaces. They are not commercial plans and do not determine whether a club uses Starter, Pro or Business.', finalTitle: 'Start with no fixed fee.', finalAccent: 'The operation remains yours.', talk: 'LET’S TALK',
  plans: {
    starter: { courtsLabel: 'Up to 4 courts', adminsLabel: '1 administrator', summary: 'For clubs with up to 4 courts that want to manage operations without a monthly subscription.', ctaLabel: 'START WITHOUT A SUBSCRIPTION', features: ['Padbol, Padel, Pickleball and Tennis', 'Unlimited players and customers', 'Public club profile, courts, schedules, rates and availability', 'Online bookings and manual booking entry', 'Matches, result entry and club ranking', 'Club-managed tournaments: registrations, teams, matches and results', 'Digital scoreboard with live control and screen or TV output', 'Operational dashboard for bookings, occupancy and revenue', 'Club PadCoins balances, transactions and redemptions', 'Compatible file import, subject to prior validation'] },
    pro: { courtsLabel: 'Up to 12 courts', adminsLabel: 'Up to 5 administrators', summary: 'For clubs that want to automate operations and grow their community.', ctaLabel: 'CHOOSE PRO', features: ['Everything in Starter', 'Automated tournaments: draws, groups, fixtures, standings, brackets and podiums', 'Reports and exports for bookings, revenue and PadCoins', 'Tournament waiting lists and opening alerts', 'Campaigns, promotions, rewards and PadCoins redemptions', 'Club memberships', 'Your own sponsors on scoreboards, tournaments and club screens', 'Segmented notifications to club players', 'Assisted migration and priority support'] },
    business: { pricePrefix: 'From', commissionPrefix: 'From', courtsLabel: '13+ courts', adminsLabel: 'Custom terms', summary: 'Multisite and custom solutions for chains, operators and licensees.', ctaLabel: 'LET’S TALK', features: ['Everything in Pro', 'Multisite scope defined with each organization', 'Centralized permissions and administration based on the project', 'Consolidated reports and network campaigns according to scope', 'Custom migration', 'Integrations and API subject to technical validation', 'Dedicated support'] },
  },
};

const RO = {
  ...EN,
  metaTitle: 'Padbol Match pentru cluburi — Planuri', metaDescription: 'Padbol Match reunește rezervările, jucătorii, meciurile, turneele, clasamentele, tabela digitală și administrarea cluburilor multisport.',
  notDefined: 'De stabilit', featured: 'CEL MAI POPULAR', perMonth: '/ lună', or: 'sau', perYear: '/ an', limits: 'Limitele planului', venueService: 'Serviciu pentru club', commissionNote: 'din operațiunile procesate prin Padbol Match',
  draft: 'VERSIUNE INTERNĂ · NEPUBLICATĂ', back: '← Pentru administratori', eyebrow: 'PADBOL MATCH PENTRU CLUBURI', title: 'Întregul tău club.', titleAccent: 'O singură platformă.', sports: 'Padbol · Padel · Pickleball · Tenis', lead: 'Rezervări, jucători, meciuri, turnee, clasamente, tabelă în direct, abonamente și administrare într-un singur loc.', start: 'ÎNCEPE FĂRĂ ABONAMENT', seePlans: 'VEZI PLANURILE', operationAria: 'Activitatea conectată a clubului', liveClub: 'CLUB ÎN DIRECT', fourSports: '4 sporturi', bookings: 'Rezervări și disponibilitate', liveMatch: 'Meci și tabelă în direct', results: 'Rezultate, clasament și revenirea jucătorilor', connected: 'O activitate conectată înainte, în timpul și după joc.',
  playerFeeAria: 'Comisioane pentru jucător', playerFeeTitle: 'JUCĂTORUL PLĂTEȘTE 0% COMISION CĂTRE PADBOL MATCH.', playerFeeText: 'Comisioanele planurilor corespund serviciului oferit clubului. Costurile Mercado Pago, Stripe sau ale altui procesator de plăți sunt separate.',
  padbolBenefit: 'BENEFICIU EXCLUSIV PENTRU CLUBURILE PADBOL', padbolOwnerTitle: 'Deții unul sau mai multe Padbol Courts?', padbolOwnerText: 'Solicită Padbol Match Pro gratuit timp de 12 luni și administrează-ți clubul dintr-o singură platformă.', padbolOwnerHint: 'Povestește-ne despre clubul tău. Echipa noastră te va contacta pentru a analiza solicitarea și pașii următori.', padbolOwnerCta: 'SOLICITĂ 12 LUNI DE PRO',
  plansEyebrow: 'PLANURI CARE CRESC ÎMPREUNĂ CU TINE', plansTitle: 'Începe cu administrarea.', plansAccent: 'Treci la Pro pentru automatizare.', finePrint: 'Limitele, prețurile, promoțiile și comisioanele depind de regiune și de configurația în vigoare. Condițiile Business se stabilesc prin contact comercial și validare tehnică.',
  scoreboardEyebrow: 'TABELA TA DIGITALĂ, INCLUSĂ ÎNCĂ DE LA STARTER', scoreboardTitle: 'Meciul în direct.', scoreboardAccent: 'Fără echipament special.', devices: 'Telefon · Tabletă · Computer · TV', scoreboardItems: ['Scor și actualizări în direct.', 'Afișare pe ecran sau televizor.', 'Control wireless de pe dispozitivele clubului.'], scoreboardNote: 'Pro adaugă sponsori proprii, turnee automatizate, rapoarte exportabile, campanii PadCoins și notificări segmentate.', scoreboardAria: 'Tabela digitală Padbol Match în timpul unui meci', scoreboardCaption: 'Tabela disponibilă în prezent în Padbol Match.',
  multisportEyebrow: 'UN CLUB. PATRU SPORTURI.', multisportTitle: 'Padbol · Padel · Pickleball · Tenis', multisportText: 'Administrează toate Padbol Courts și celelalte terenuri din aceeași platformă, chiar dacă în club se practică sporturi diferite.',
  automationEyebrow: 'STARTER ADMINISTREAZĂ. PRO AUTOMATIZEAZĂ.', automationTitle: 'Mai multă activitate în club.', automationAccent: 'Mai puține sarcini repetitive.', automation: [['Turnee automatizate', 'Tragere la sorți → grupe → meciuri → rezultate → clasament → tablou → finale.'], ['Generează venituri noi', 'Abonamente, promoții și spații proprii pentru sponsori.'], ['Fidelizează jucătorii', 'PadCoins, campanii și beneficii configurate de club.'], ['Redu costul platformei', 'Starter: 1% · Pro: 0,65%. Valorile pot fi administrate în funcție de regiune.']],
  migrationEyebrow: 'FOLOSEȘTI DEJA ALT SISTEM?', migrationTitle: 'Nu începi de la zero.', migrationText: 'Putem importa informații care aparțin în mod legitim clubului și au un format compatibil. Stabilim domeniul importului înainte de a începe.', migration: [['Starter', 'Import de fișiere compatibile, supus validării.'], ['Pro', 'Migrare asistată.'], ['Business', 'Migrare personalizată.']],
  growthAria: 'Instrumente de dezvoltare Pro', membershipTitle: 'CREEAZĂ-ȚI PROPRIUL ABONAMENT', membershipText: 'Stabilește prețul, durata, beneficiile, reducerile, programul, prioritatea, rezervările incluse și PadCoins. Este abonamentul propriu al clubului, separat de orice viitor abonament global al jucătorului.', screensTitle: 'TRANSFORMĂ ECRANELE ÎNTR-UN ACTIV', screensText: 'Administrează sponsorii proprii pe tabelă, TV, în turnee și în spațiile locale disponibile. Inventarul clubului rămâne separat de inventarul Global Padbol Match și de cel al FIPA.',
  experiencesEyebrow: 'CINCI EXPERIENȚE. UN SINGUR PRODUS.', experiencesText: 'Acestea sunt interfețe vizuale Padbol Match. Nu sunt planuri comerciale și nu stabilesc dacă un club folosește Starter, Pro sau Business.', finalTitle: 'Începe fără cost fix.', finalAccent: 'Activitatea rămâne a ta.', talk: 'HAI SĂ VORBIM',
  plans: {
    starter: { courtsLabel: 'Până la 4 terenuri', adminsLabel: '1 administrator', summary: 'Pentru cluburi cu cel mult 4 terenuri care vor să își administreze activitatea fără abonament lunar.', ctaLabel: 'ÎNCEPE FĂRĂ ABONAMENT', features: ['Padbol, Padel, Pickleball și Tenis', 'Jucători și clienți nelimitați', 'Profil public al clubului, terenuri, programe, tarife și disponibilitate', 'Rezervări online și introducerea manuală a rezervărilor', 'Meciuri, introducerea rezultatelor și clasamentul clubului', 'Turnee administrate de club: înscrieri, echipe, meciuri și rezultate', 'Tabelă digitală cu control în direct și afișare pe ecran sau TV', 'Panou operațional pentru rezervări, grad de ocupare și venituri', 'Solduri, tranzacții și utilizări PadCoins ale clubului', 'Import de fișiere compatibile, supus validării prealabile'] },
    pro: { courtsLabel: 'Până la 12 terenuri', adminsLabel: 'Până la 5 administratori', summary: 'Pentru cluburi care vor să automatizeze activitatea și să își dezvolte comunitatea.', ctaLabel: 'ALEGE PRO', features: ['Tot ce include Starter', 'Turnee automatizate: trageri la sorți, grupe, program, clasament, tablouri și podiumuri', 'Rapoarte și exporturi pentru rezervări, venituri și PadCoins', 'Liste de așteptare pentru turnee și notificări la deschidere', 'Campanii, promoții, recompense și utilizări PadCoins', 'Abonamente proprii ale clubului', 'Sponsori proprii pe tabelă, în turnee și pe ecranele clubului', 'Notificări segmentate pentru jucătorii clubului', 'Migrare asistată și asistență prioritară'] },
    business: { pricePrefix: 'De la', commissionPrefix: 'De la', courtsLabel: 'Cel puțin 13 terenuri', adminsLabel: 'Condiții personalizate', summary: 'Soluții multisite și personalizate pentru lanțuri, operatori și licențiați.', ctaLabel: 'HAI SĂ VORBIM', features: ['Tot ce include Pro', 'Domeniu multisite stabilit cu fiecare organizație', 'Permisiuni și administrare centralizată în funcție de proiect', 'Rapoarte consolidate și campanii de rețea în funcție de domeniu', 'Migrare personalizată', 'Integrări și API supuse validării tehnice', 'Asistență dedicată'] },
  },
};

export function venuePlansCopy(language) {
  const code = String(language || '').toLowerCase();
  if (code.startsWith('es')) return ES;
  if (code.startsWith('ro')) return RO;
  return EN;
}
