const ES = {
  metaTitle: 'Padbol Match para clubes — Planes',
  metaDescription: 'Padbol Match reúne reservas, jugadores, partidos, torneos, rankings, marcador digital y gestión de clubes multideporte.',
  notDefined: 'A definir', featured: 'MÁS ELEGIDO', perMonth: '/ mes', or: 'o', perYear: '/ año', limits: 'Límites del plan', venueService: 'Servicio a la sede', commissionNote: 'sobre operaciones procesadas mediante Padbol Match',
  draft: 'BORRADOR INTERNO · NO PUBLICADO', back: '← Para administradores', eyebrow: 'PADBOL MATCH PARA CLUBES', title: 'Todo tu club.', titleAccent: 'Una sola plataforma.', sports: 'Padbol · Padel · Pickleball · Tenis', lead: 'Reservas, jugadores, partidos, torneos, rankings, marcador en vivo, membresías y gestión desde un mismo lugar.', start: 'EMPEZAR SIN ABONO', seePlans: 'VER PLANES', operationAria: 'Operación conectada del club', liveClub: 'CLUB EN VIVO', fourSports: '4 deportes', bookings: 'Reservas y disponibilidad', liveMatch: 'Partido y marcador en vivo', results: 'Resultados, ranking y retorno', connected: 'Una operación conectada antes, durante y después de jugar.',
  playerFeeAria: 'Comisiones al jugador', playerFeeTitle: 'EL JUGADOR PAGA 0% DE COMISIÓN A PADBOL MATCH.', playerFeeText: 'Las comisiones de los planes corresponden al servicio prestado a la sede. Los costos de Mercado Pago, Stripe u otro procesador son independientes.',
  padbolBenefit: 'BENEFICIO EXCLUSIVO PARA SEDES PADBOL', padbolOwnerTitle: '¿Sos propietario de una o más Padbol Courts?', padbolOwnerText: 'Solicitá Padbol Match Pro sin cargo durante 12 meses y administrá tu sede desde una sola plataforma.', padbolOwnerHint: 'Contanos sobre tu sede. Nuestro equipo te contactará para evaluar la solicitud y los próximos pasos.', padbolOwnerCta: 'SOLICITAR 12 MESES PRO',
  plansEyebrow: 'PLANES PARA CRECER A TU RITMO', plansTitle: 'Empezá administrando.', plansAccent: 'Pasá a Pro para automatizar.', finePrint: 'Los límites, precios, promociones y comisiones dependen de la región y de la configuración vigente. Business se define por contacto comercial y validación técnica.',
  scoreboardEyebrow: 'TU MARCADOR DIGITAL, INCLUIDO DESDE STARTER', scoreboardTitle: 'El partido en vivo.', scoreboardAccent: 'Sin equipamiento específico.', devices: 'Teléfono · Tablet · Computadora · TV', scoreboardItems: ['Score y actualización en vivo.', 'Visualización en pantalla o TV.', 'Uso inalámbrico desde los dispositivos del club.'], scoreboardNote: 'Pro suma sponsors propios, torneos automatizados, reportes exportables, campañas PadCoins y notificaciones segmentadas.', scoreboardAria: 'Marcador digital de Padbol Match durante un partido', scoreboardCaption: 'Marcador actualmente disponible en Padbol Match.',
  multisportEyebrow: 'UN CLUB. CUATRO DEPORTES.', multisportTitle: 'Padbol · Padel · Pickleball · Tenis', multisportText: 'Administrá todas tus Padbol Courts y demás canchas desde una misma plataforma, aunque tu club practique diferentes deportes.',
  automationEyebrow: 'STARTER ADMINISTRA. PRO AUTOMATIZA.', automationTitle: 'Más movimiento para tu club.', automationAccent: 'Menos tareas repetidas.', automation: [
    ['Torneos automáticos', 'Sorteo → zonas → partidos → resultados → clasificación → cruces → finales.'],
    ['Generá nuevos ingresos', 'Membresías, promociones y espacios propios para sponsors.'],
    ['Fidelizá jugadores', 'PadCoins, campañas y beneficios configurados por el club.'],
    ['Reducí el costo de plataforma', 'Starter: 1% · Pro: 0,65%. Valores administrables por región.'],
  ],
  migrationEyebrow: '¿YA USÁS OTRO SISTEMA?', migrationTitle: 'No empezás de cero.', migrationText: 'Podemos importar información que pertenezca legítimamente a la sede y que tenga un formato compatible. El alcance se valida antes de comenzar.', migration: [['Starter', 'Importación de archivos compatibles, sujeta a validación.'], ['Pro', 'Migración asistida.'], ['Business', 'Migración personalizada.']],
  growthAria: 'Herramientas de crecimiento Pro', membershipTitle: 'CREÁ TU PROPIA MEMBRESÍA', membershipText: 'Definí precio, duración, beneficios, descuentos, horarios, prioridad, reservas incluidas y PadCoins. Es una membresía propia del club, separada de cualquier futura membresía global del jugador.', screensTitle: 'CONVERTÍ TUS PANTALLAS EN UN ACTIVO', screensText: 'Gestioná sponsors propios en marcador, TV, torneos y espacios locales disponibles. El inventario de la sede se mantiene separado del inventario Global Padbol Match y del de FIPA.',
  experiencesEyebrow: 'CINCO EXPERIENCIAS. UN SOLO PRODUCTO.', experiencesText: 'Son interfaces visuales de Padbol Match. No son planes comerciales y no determinan si un club usa Starter, Pro o Business.', finalTitle: 'Empezá sin costo fijo.', finalAccent: 'La operación sigue siendo tuya.', talk: 'HABLEMOS',
  plans: {
    starter: { courtsLabel: 'Hasta 4 canchas', adminsLabel: '1 administrador', summary: 'Para clubes de hasta 4 canchas que quieren administrar su operación sin abono mensual.', ctaLabel: 'EMPEZAR SIN ABONO', features: ['Padbol, Padel, Pickleball y Tenis', 'Jugadores y clientes ilimitados', 'Perfil público de la sede, canchas, horarios, tarifas y disponibilidad', 'Reservas online y carga manual de reservas', 'Partidos, carga de resultados y ranking del club', 'Torneos administrados por la sede: inscripciones, equipos, partidos y resultados', 'Marcador digital con control en vivo y salida para pantalla o TV', 'Panel operativo de reservas, ocupación e ingresos', 'Consulta de saldos, movimientos y canjes de PadCoins de la sede', 'Importación de archivos compatibles, sujeta a validación previa'] },
    pro: { courtsLabel: 'Hasta 12 canchas', adminsLabel: 'Hasta 5 administradores', summary: 'Para clubes que quieren automatizar la operación y hacer crecer su comunidad.', ctaLabel: 'ELEGIR PRO', features: ['Todo lo incluido en Starter', 'Torneos automatizados: sorteos, zonas, fixture, clasificación, llaves y podios', 'Reportes y exportaciones de reservas, ingresos y PadCoins', 'Listas de espera de torneos y avisos de apertura', 'Creación de campañas, promociones, premios y canjes con PadCoins', 'Membresías propias del club', 'Sponsors propios en marcador, torneos y pantallas de la sede', 'Notificaciones segmentadas a jugadores de la sede', 'Migración asistida y soporte prioritario'] },
    business: { pricePrefix: 'Desde', commissionPrefix: 'Desde', courtsLabel: '13+ canchas', adminsLabel: 'Condiciones personalizadas', summary: 'Soluciones multisede y personalizadas para cadenas, operadores y licenciatarios.', ctaLabel: 'HABLEMOS', features: ['Todo lo incluido en Pro', 'Alcance multisede definido con cada organización', 'Permisos y administración centralizada según proyecto', 'Reportes consolidados y campañas de red según alcance', 'Migración personalizada', 'Integraciones y API sujetas a validación técnica', 'Soporte dedicado'] },
  },
};

const EN = {
  ...ES,
  metaTitle: 'Padbol Match for clubs — Plans', metaDescription: 'Padbol Match brings bookings, players, matches, tournaments, rankings, digital scoreboard and multisport club management together.',
  notDefined: 'To be defined', featured: 'MOST POPULAR', perMonth: '/ month', or: 'or', perYear: '/ year', limits: 'Plan limits', venueService: 'Service for the club', commissionNote: 'on transactions processed through Padbol Match',
  draft: 'INTERNAL DRAFT · NOT PUBLISHED', back: '← For administrators', eyebrow: 'PADBOL MATCH FOR CLUBS', title: 'Your entire club.', titleAccent: 'One platform.', sports: 'Padbol · Padel · Pickleball · Tennis', lead: 'Bookings, players, matches, tournaments, rankings, live scoreboard, memberships and management in one place.', start: 'START WITHOUT A SUBSCRIPTION', seePlans: 'VIEW PLANS', operationAria: 'Connected club operation', liveClub: 'CLUB LIVE', fourSports: '4 sports', bookings: 'Bookings and availability', liveMatch: 'Live match and scoreboard', results: 'Results, ranking and return visits', connected: 'One connected operation before, during and after play.',
  playerFeeAria: 'Player fees', playerFeeTitle: 'PLAYERS PAY 0% COMMISSION TO PADBOL MATCH.', playerFeeText: 'Plan commissions correspond to the service provided to the club. Mercado Pago, Stripe or other payment processor costs are separate.',
  padbolBenefit: 'EXCLUSIVE BENEFIT FOR PADBOL CLUBS', padbolOwnerTitle: 'Do you own one or more Padbol Courts?', padbolOwnerText: 'Apply for Padbol Match Pro free for 12 months and manage your club from one platform.', padbolOwnerHint: 'Tell us about your club. Our team will contact you to review the application and next steps.', padbolOwnerCta: 'APPLY FOR 12 MONTHS OF PRO',
  plansEyebrow: 'PLANS THAT GROW WITH YOU', plansTitle: 'Start by managing.', plansAccent: 'Move to Pro to automate.', finePrint: 'Limits, prices, promotions and commissions depend on the region and current configuration. Business terms are defined through commercial contact and technical validation.',
  scoreboardEyebrow: 'YOUR DIGITAL SCOREBOARD, INCLUDED FROM STARTER', scoreboardTitle: 'The match live.', scoreboardAccent: 'No special equipment.', devices: 'Phone · Tablet · Computer · TV', scoreboardItems: ['Live scoring and updates.', 'Display on a screen or TV.', 'Wireless control from club devices.'], scoreboardNote: 'Pro adds your own sponsors, automated tournaments, exportable reports, PadCoins campaigns and segmented notifications.', scoreboardAria: 'Padbol Match digital scoreboard during a match', scoreboardCaption: 'Scoreboard currently available in Padbol Match.',
  multisportEyebrow: 'ONE CLUB. FOUR SPORTS.', multisportTitle: 'Padbol · Padel · Pickleball · Tennis', multisportText: 'Manage every Padbol Court and other playing court from the same platform, even when your club offers different sports.',
  automationEyebrow: 'STARTER MANAGES. PRO AUTOMATES.', automationTitle: 'More activity for your club.', automationAccent: 'Fewer repetitive tasks.', automation: [['Automated tournaments', 'Draw → groups → matches → results → standings → brackets → finals.'], ['Create new revenue', 'Memberships, promotions and your own sponsor placements.'], ['Build player loyalty', 'PadCoins, campaigns and benefits configured by the club.'], ['Reduce platform cost', 'Starter: 1% · Pro: 0.65%. Values can be managed by region.']],
  migrationEyebrow: 'ALREADY USING ANOTHER SYSTEM?', migrationTitle: 'You do not start from zero.', migrationText: 'We can import information that legitimately belongs to the club and uses a compatible format. Scope is validated before work begins.', migration: [['Starter', 'Compatible file import, subject to validation.'], ['Pro', 'Assisted migration.'], ['Business', 'Custom migration.']],
  growthAria: 'Pro growth tools', membershipTitle: 'CREATE YOUR OWN MEMBERSHIP', membershipText: 'Define price, duration, benefits, discounts, schedules, priority, included bookings and PadCoins. This is the club’s own membership, separate from any future global player membership.', screensTitle: 'TURN YOUR SCREENS INTO AN ASSET', screensText: 'Manage your own sponsors on the scoreboard, TV, tournaments and available local placements. Club inventory remains separate from Global Padbol Match and FIPA inventory.',
  experiencesEyebrow: 'FIVE EXPERIENCES. ONE PRODUCT.', experiencesText: 'These are Padbol Match visual interfaces. They are not commercial plans and do not determine whether a club uses Starter, Pro or Business.', finalTitle: 'Start with no fixed fee.', finalAccent: 'The operation remains yours.', talk: 'LET’S TALK',
  plans: {
    starter: { courtsLabel: 'Up to 4 courts', adminsLabel: '1 administrator', summary: 'For clubs with up to 4 courts that want to manage operations without a monthly subscription.', ctaLabel: 'START WITHOUT A SUBSCRIPTION', features: ['Padbol, Padel, Pickleball and Tennis', 'Unlimited players and customers', 'Public club profile, courts, schedules, rates and availability', 'Online bookings and manual booking entry', 'Matches, result entry and club ranking', 'Club-managed tournaments: registrations, teams, matches and results', 'Digital scoreboard with live control and screen or TV output', 'Operational dashboard for bookings, occupancy and revenue', 'Club PadCoins balances, transactions and redemptions', 'Compatible file import, subject to prior validation'] },
    pro: { courtsLabel: 'Up to 12 courts', adminsLabel: 'Up to 5 administrators', summary: 'For clubs that want to automate operations and grow their community.', ctaLabel: 'CHOOSE PRO', features: ['Everything in Starter', 'Automated tournaments: draws, groups, fixtures, standings, brackets and podiums', 'Reports and exports for bookings, revenue and PadCoins', 'Tournament waiting lists and opening alerts', 'Campaigns, promotions, rewards and PadCoins redemptions', 'Club memberships', 'Your own sponsors on scoreboards, tournaments and club screens', 'Segmented notifications to club players', 'Assisted migration and priority support'] },
    business: { pricePrefix: 'From', commissionPrefix: 'From', courtsLabel: '13+ courts', adminsLabel: 'Custom terms', summary: 'Multisite and custom solutions for chains, operators and licensees.', ctaLabel: 'LET’S TALK', features: ['Everything in Pro', 'Multisite scope defined with each organization', 'Centralized permissions and administration based on the project', 'Consolidated reports and network campaigns according to scope', 'Custom migration', 'Integrations and API subject to technical validation', 'Dedicated support'] },
  },
};

const RO = {
  ...EN,
  metaTitle: 'Padbol Match pentru cluburi — Planuri', metaDescription: 'Padbol Match reunește rezervările, jucătorii, meciurile, turneele, clasamentele, tabela digitală și administrarea cluburilor multisport.',
  notDefined: 'De stabilit', featured: 'CEL MAI POPULAR', perMonth: '/ lună', or: 'sau', perYear: '/ an', limits: 'Limitele planului', venueService: 'Serviciu pentru club', commissionNote: 'din operațiunile procesate prin Padbol Match',
  draft: 'VERSIUNE INTERNĂ · NEPUBLICATĂ', back: '← Pentru administratori', eyebrow: 'PADBOL MATCH PENTRU CLUBURI', title: 'Întregul tău club.', titleAccent: 'O singură platformă.', sports: 'Padbol · Padel · Pickleball · Tenis', lead: 'Rezervări, jucători, meciuri, turnee, clasamente, tabelă în direct, abonamente și administrare într-un singur loc.', start: 'ÎNCEPE FĂRĂ ABONAMENT', seePlans: 'VEZI PLANURILE', operationAria: 'Activitatea conectată a clubului', liveClub: 'CLUB ÎN DIRECT', fourSports: '4 sporturi', bookings: 'Rezervări și disponibilitate', liveMatch: 'Meci și tabelă în direct', results: 'Rezultate, clasament și revenirea jucătorilor', connected: 'O activitate conectată înainte, în timpul și după joc.',
  playerFeeAria: 'Comisioane pentru jucător', playerFeeTitle: 'JUCĂTORUL PLĂTEȘTE 0% COMISION CĂTRE PADBOL MATCH.', playerFeeText: 'Comisioanele planurilor corespund serviciului oferit clubului. Costurile Mercado Pago, Stripe sau ale altui procesator de plăți sunt separate.',
  padbolBenefit: 'BENEFICIU EXCLUSIV PENTRU CLUBURILE PADBOL', padbolOwnerTitle: 'Deții unul sau mai multe Padbol Courts?', padbolOwnerText: 'Solicită Padbol Match Pro gratuit timp de 12 luni și administrează-ți clubul dintr-o singură platformă.', padbolOwnerHint: 'Povestește-ne despre clubul tău. Echipa noastră te va contacta pentru a analiza solicitarea și pașii următori.', padbolOwnerCta: 'SOLICITĂ 12 LUNI DE PRO',
  plansEyebrow: 'PLANURI CARE CRESC ÎMPREUNĂ CU TINE', plansTitle: 'Începe cu administrarea.', plansAccent: 'Treci la Pro pentru automatizare.', finePrint: 'Limitele, prețurile, promoțiile și comisioanele depind de regiune și de configurația în vigoare. Condițiile Business se stabilesc prin contact comercial și validare tehnică.',
  scoreboardEyebrow: 'TABELA TA DIGITALĂ, INCLUSĂ ÎNCĂ DE LA STARTER', scoreboardTitle: 'Meciul în direct.', scoreboardAccent: 'Fără echipament special.', devices: 'Telefon · Tabletă · Computer · TV', scoreboardItems: ['Scor și actualizări în direct.', 'Afișare pe ecran sau televizor.', 'Control wireless de pe dispozitivele clubului.'], scoreboardNote: 'Pro adaugă sponsori proprii, turnee automatizate, rapoarte exportabile, campanii PadCoins și notificări segmentate.', scoreboardAria: 'Tabela digitală Padbol Match în timpul unui meci', scoreboardCaption: 'Tabela disponibilă în prezent în Padbol Match.',
  multisportEyebrow: 'UN CLUB. PATRU SPORTURI.', multisportTitle: 'Padbol · Padel · Pickleball · Tenis', multisportText: 'Administrează toate Padbol Courts și celelalte terenuri din aceeași platformă, chiar dacă în club se practică sporturi diferite.',
  automationEyebrow: 'STARTER ADMINISTREAZĂ. PRO AUTOMATIZEAZĂ.', automationTitle: 'Mai multă activitate în club.', automationAccent: 'Mai puține sarcini repetitive.', automation: [['Turnee automatizate', 'Tragere la sorți → grupe → meciuri → rezultate → clasament → tablou → finale.'], ['Generează venituri noi', 'Abonamente, promoții și spații proprii pentru sponsori.'], ['Fidelizează jucătorii', 'PadCoins, campanii și beneficii configurate de club.'], ['Redu costul platformei', 'Starter: 1% · Pro: 0,65%. Valorile pot fi administrate în funcție de regiune.']],
  migrationEyebrow: 'FOLOSEȘTI DEJA ALT SISTEM?', migrationTitle: 'Nu începi de la zero.', migrationText: 'Putem importa informații care aparțin în mod legitim clubului și au un format compatibil. Stabilim domeniul importului înainte de a începe.', migration: [['Starter', 'Import de fișiere compatibile, supus validării.'], ['Pro', 'Migrare asistată.'], ['Business', 'Migrare personalizată.']],
  growthAria: 'Instrumente de dezvoltare Pro', membershipTitle: 'CREEAZĂ-ȚI PROPRIUL ABONAMENT', membershipText: 'Stabilește prețul, durata, beneficiile, reducerile, programul, prioritatea, rezervările incluse și PadCoins. Este abonamentul propriu al clubului, separat de orice viitor abonament global al jucătorului.', screensTitle: 'TRANSFORMĂ ECRANELE ÎNTR-UN ACTIV', screensText: 'Administrează sponsorii proprii pe tabelă, TV, în turnee și în spațiile locale disponibile. Inventarul clubului rămâne separat de inventarul Global Padbol Match și de cel al FIPA.',
  experiencesEyebrow: 'CINCI EXPERIENȚE. UN SINGUR PRODUS.', experiencesText: 'Acestea sunt interfețe vizuale Padbol Match. Nu sunt planuri comerciale și nu stabilesc dacă un club folosește Starter, Pro sau Business.', finalTitle: 'Începe fără cost fix.', finalAccent: 'Activitatea rămâne a ta.', talk: 'HAI SĂ VORBIM',
  plans: {
    starter: { courtsLabel: 'Până la 4 terenuri', adminsLabel: '1 administrator', summary: 'Pentru cluburi cu cel mult 4 terenuri care vor să își administreze activitatea fără abonament lunar.', ctaLabel: 'ÎNCEPE FĂRĂ ABONAMENT', features: ['Padbol, Padel, Pickleball și Tenis', 'Jucători și clienți nelimitați', 'Profil public al clubului, terenuri, programe, tarife și disponibilitate', 'Rezervări online și introducerea manuală a rezervărilor', 'Meciuri, introducerea rezultatelor și clasamentul clubului', 'Turnee administrate de club: înscrieri, echipe, meciuri și rezultate', 'Tabelă digitală cu control în direct și afișare pe ecran sau TV', 'Panou operațional pentru rezervări, grad de ocupare și venituri', 'Solduri, tranzacții și utilizări PadCoins ale clubului', 'Import de fișiere compatibile, supus validării prealabile'] },
    pro: { courtsLabel: 'Până la 12 terenuri', adminsLabel: 'Până la 5 administratori', summary: 'Pentru cluburi care vor să automatizeze activitatea și să își dezvolte comunitatea.', ctaLabel: 'ALEGE PRO', features: ['Tot ce include Starter', 'Turnee automatizate: trageri la sorți, grupe, program, clasament, tablouri și podiumuri', 'Rapoarte și exporturi pentru rezervări, venituri și PadCoins', 'Liste de așteptare pentru turnee și notificări la deschidere', 'Campanii, promoții, recompense și utilizări PadCoins', 'Abonamente proprii ale clubului', 'Sponsori proprii pe tabelă, în turnee și pe ecranele clubului', 'Notificări segmentate pentru jucătorii clubului', 'Migrare asistată și asistență prioritară'] },
    business: { pricePrefix: 'De la', commissionPrefix: 'De la', courtsLabel: 'Cel puțin 13 terenuri', adminsLabel: 'Condiții personalizate', summary: 'Soluții multisite și personalizate pentru lanțuri, operatori și licențiați.', ctaLabel: 'HAI SĂ VORBIM', features: ['Tot ce include Pro', 'Domeniu multisite stabilit cu fiecare organizație', 'Permisiuni și administrare centralizată în funcție de proiect', 'Rapoarte consolidate și campanii de rețea în funcție de domeniu', 'Migrare personalizată', 'Integrări și API supuse validării tehnice', 'Asistență dedicată'] },
  },
};

const CS = {
  ...EN,
  metaTitle: 'Padbol Match pro kluby — Tarify', metaDescription: 'Padbol Match propojuje rezervace, hráče, zápasy, turnaje, žebříčky, digitální výsledkovou tabuli a správu multisportovních klubů.',
  notDefined: 'Bude upřesněno', featured: 'NEJOBLÍBENĚJŠÍ', perMonth: '/ měsíc', or: 'nebo', perYear: '/ rok', limits: 'Limity tarifu', venueService: 'Služba pro klub', commissionNote: 'z transakcí zpracovaných prostřednictvím Padbol Match',
  draft: 'INTERNÍ NÁVRH · NEZVEŘEJNĚNO', back: '← Pro správce', eyebrow: 'PADBOL MATCH PRO KLUBY', title: 'Celý váš klub.', titleAccent: 'Jedna platforma.', sports: 'Padbol · Padel · Pickleball · Tenis', lead: 'Rezervace, hráči, zápasy, turnaje, žebříčky, živá výsledková tabule, členství a správa na jednom místě.', start: 'ZAČÍT BEZ PAUŠÁLU', seePlans: 'ZOBRAZIT TARIFY', operationAria: 'Propojený provoz klubu', liveClub: 'KLUB ŽIVĚ', fourSports: '4 sporty', bookings: 'Rezervace a dostupnost', liveMatch: 'Živý zápas a výsledková tabule', results: 'Výsledky, žebříček a návrat hráčů', connected: 'Jeden propojený provoz před hrou, během ní i po ní.',
  playerFeeAria: 'Poplatky pro hráče', playerFeeTitle: 'HRÁČI PLATÍ PADBOL MATCH PROVIZI 0 %.', playerFeeText: 'Provize jednotlivých tarifů se vztahují ke službě poskytované klubu. Poplatky Mercado Pago, Stripe nebo jiného poskytovatele plateb jsou účtovány zvlášť.',
  padbolBenefit: 'EXKLUZIVNÍ VÝHODA PRO PADBOL KLUBY', padbolOwnerTitle: 'Provozujete jeden nebo více Padbol Courts?', padbolOwnerText: 'Požádejte o Padbol Match Pro zdarma na 12 měsíců a spravujte svůj klub z jediné platformy.', padbolOwnerHint: 'Řekněte nám o svém klubu. Náš tým vás kontaktuje, aby posoudil žádost a domluvil další kroky.', padbolOwnerCta: 'POŽÁDAT O 12 MĚSÍCŮ PRO',
  plansEyebrow: 'TARIFY, KTERÉ ROSTOU S VÁMI', plansTitle: 'Začněte správou.', plansAccent: 'S tarifem Pro vše zautomatizujete.', finePrint: 'Limity, ceny, akce a provize závisí na regionu a aktuálním nastavení. Podmínky tarifu Business se stanovují po obchodní konzultaci a technickém ověření.',
  scoreboardEyebrow: 'DIGITÁLNÍ VÝSLEDKOVÁ TABULE JIŽ V TARIFU STARTER', scoreboardTitle: 'Zápas živě.', scoreboardAccent: 'Bez speciálního vybavení.', devices: 'Telefon · Tablet · Počítač · TV', scoreboardItems: ['Živé skóre a aktualizace.', 'Zobrazení na obrazovce nebo TV.', 'Bezdrátové ovládání ze zařízení klubu.'], scoreboardNote: 'Tarif Pro přidává vlastní sponzory, automatizované turnaje, exportovatelné reporty, kampaně PadCoins a cílená oznámení.', scoreboardAria: 'Digitální výsledková tabule Padbol Match během zápasu', scoreboardCaption: 'Výsledková tabule, která je nyní dostupná v Padbol Match.',
  multisportEyebrow: 'JEDEN KLUB. ČTYŘI SPORTY.', multisportTitle: 'Padbol · Padel · Pickleball · Tenis', multisportText: 'Spravujte všechny své Padbol Courts i ostatní kurty z jediné platformy, i když váš klub nabízí více sportů.',
  automationEyebrow: 'STARTER SPRAVUJE. PRO AUTOMATIZUJE.', automationTitle: 'Více aktivity pro váš klub.', automationAccent: 'Méně opakujících se úkolů.', automation: [['Automatizované turnaje', 'Losování → skupiny → zápasy → výsledky → pořadí → pavouk → finále.'], ['Nové zdroje příjmů', 'Členství, akce a vlastní reklamní prostory pro sponzory.'], ['Věrnější hráči', 'PadCoins, kampaně a výhody nastavené klubem.'], ['Nižší náklady na platformu', 'Starter: 1 % · Pro: 0,65 %. Hodnoty lze upravit podle regionu.']],
  migrationEyebrow: 'UŽ POUŽÍVÁTE JINÝ SYSTÉM?', migrationTitle: 'Nemusíte začínat od nuly.', migrationText: 'Můžeme importovat údaje, které klubu oprávněně patří a jsou v kompatibilním formátu. Rozsah ověříme před zahájením práce.', migration: [['Starter', 'Import kompatibilních souborů po ověření.'], ['Pro', 'Asistovaná migrace.'], ['Business', 'Migrace na míru.']],
  growthAria: 'Nástroje tarifu Pro pro růst', membershipTitle: 'VYTVOŘTE VLASTNÍ ČLENSTVÍ', membershipText: 'Nastavte cenu, délku, výhody, slevy, časy, přednostní přístup, zahrnuté rezervace a PadCoins. Jde o vlastní členství klubu, oddělené od případného budoucího globálního členství hráče.', screensTitle: 'PROMĚŇTE OBRAZOVKY V AKTIVUM', screensText: 'Spravujte vlastní sponzory na výsledkové tabuli, TV, v turnajích a dostupných místních reklamních plochách. Reklamní prostor klubu zůstává oddělený od prostoru Global Padbol Match a FIPA.',
  experiencesEyebrow: 'PĚT PROSTŘEDÍ. JEDEN PRODUKT.', experiencesText: 'Jde o vizuální rozhraní Padbol Match. Nejsou to obchodní tarify a neurčují, zda klub používá Starter, Pro nebo Business.', finalTitle: 'Začněte bez pevného poplatku.', finalAccent: 'Provoz zůstává ve vašich rukou.', talk: 'KONTAKTUJTE NÁS',
  plans: {
    starter: { courtsLabel: 'Až 4 kurty', adminsLabel: '1 správce', summary: 'Pro kluby s nejvýše 4 kurty, které chtějí řídit provoz bez měsíčního paušálu.', ctaLabel: 'ZAČÍT BEZ PAUŠÁLU', features: ['Padbol, Padel, Pickleball a Tenis', 'Neomezený počet hráčů a zákazníků', 'Veřejný profil klubu, kurty, otevírací doba, ceny a dostupnost', 'Online rezervace i ruční zadávání rezervací', 'Zápasy, zadávání výsledků a klubový žebříček', 'Turnaje spravované klubem: registrace, týmy, zápasy a výsledky', 'Digitální výsledková tabule s živým ovládáním a výstupem na obrazovku nebo TV', 'Provozní přehled rezervací, obsazenosti a příjmů', 'Zůstatky, pohyby a uplatnění klubových PadCoins', 'Import kompatibilních souborů po předchozím ověření'] },
    pro: { courtsLabel: 'Až 12 kurtů', adminsLabel: 'Až 5 správců', summary: 'Pro kluby, které chtějí automatizovat provoz a rozvíjet svou komunitu.', ctaLabel: 'ZVOLIT PRO', features: ['Vše z tarifu Starter', 'Automatizované turnaje: losování, skupiny, rozpis, pořadí, pavouk a stupně vítězů', 'Reporty a exporty rezervací, příjmů a PadCoins', 'Čekací listiny turnajů a upozornění při uvolnění místa', 'Kampaně, akce, odměny a uplatnění PadCoins', 'Vlastní klubová členství', 'Vlastní sponzoři na výsledkové tabuli, v turnajích a na obrazovkách klubu', 'Cílená oznámení hráčům klubu', 'Asistovaná migrace a prioritní podpora'] },
    business: { pricePrefix: 'Od', commissionPrefix: 'Od', courtsLabel: '13 a více kurtů', adminsLabel: 'Podmínky na míru', summary: 'Řešení na míru pro sítě klubů, provozovatele a držitele licencí.', ctaLabel: 'KONTAKTUJTE NÁS', features: ['Vše z tarifu Pro', 'Rozsah pro více provozoven stanovený s každou organizací', 'Centralizovaná oprávnění a správa podle projektu', 'Souhrnné reporty a síťové kampaně podle dohodnutého rozsahu', 'Migrace na míru', 'Integrace a API po technickém ověření', 'Vyhrazená podpora'] },
  },
};

const PT_BR = {
  ...EN,
  metaTitle: 'Padbol Match para clubes — Planos', metaDescription: 'O Padbol Match reúne reservas, jogadores, partidas, torneios, rankings, placar digital e gestão de clubes multiesportivos.',
  notDefined: 'A definir', featured: 'MAIS ESCOLHIDO', perMonth: '/ mês', or: 'ou', perYear: '/ ano', limits: 'Limites do plano', venueService: 'Serviço para o clube', commissionNote: 'sobre operações processadas pelo Padbol Match',
  draft: 'RASCUNHO INTERNO · NÃO PUBLICADO', back: '← Para administradores', eyebrow: 'PADBOL MATCH PARA CLUBES', title: 'Todo o seu clube.', titleAccent: 'Uma só plataforma.', sports: 'Padbol · Padel · Pickleball · Tênis', lead: 'Reservas, jogadores, partidas, torneios, rankings, placar ao vivo, planos de associação e gestão em um só lugar.', start: 'COMEÇAR SEM MENSALIDADE', seePlans: 'VER PLANOS', operationAria: 'Operação integrada do clube', liveClub: 'CLUBE AO VIVO', fourSports: '4 esportes', bookings: 'Reservas e disponibilidade', liveMatch: 'Partida e placar ao vivo', results: 'Resultados, ranking e retorno dos jogadores', connected: 'Uma operação integrada antes, durante e depois do jogo.',
  playerFeeAria: 'Taxas para o jogador', playerFeeTitle: 'O JOGADOR PAGA 0% DE COMISSÃO AO PADBOL MATCH.', playerFeeText: 'As comissões dos planos correspondem ao serviço prestado ao clube. Os custos do Mercado Pago, Stripe ou de outro processador de pagamentos são cobrados separadamente.',
  padbolBenefit: 'BENEFÍCIO EXCLUSIVO PARA CLUBES DE PADBOL', padbolOwnerTitle: 'Você administra um ou mais Padbol Courts?', padbolOwnerText: 'Solicite o Padbol Match Pro grátis por 12 meses e administre seu clube em uma só plataforma.', padbolOwnerHint: 'Conte-nos sobre o seu clube. Nossa equipe entrará em contato para analisar a solicitação e os próximos passos.', padbolOwnerCta: 'SOLICITAR 12 MESES DE PRO',
  plansEyebrow: 'PLANOS QUE CRESCEM COM VOCÊ', plansTitle: 'Comece administrando.', plansAccent: 'Passe para o Pro e automatize.', finePrint: 'Limites, preços, promoções e comissões dependem da região e da configuração vigente. As condições do Business são definidas por contato comercial e validação técnica.',
  scoreboardEyebrow: 'SEU PLACAR DIGITAL, INCLUÍDO DESDE O STARTER', scoreboardTitle: 'A partida ao vivo.', scoreboardAccent: 'Sem equipamento específico.', devices: 'Celular · Tablet · Computador · TV', scoreboardItems: ['Placar e atualizações ao vivo.', 'Exibição em tela ou TV.', 'Controle sem fio pelos dispositivos do clube.'], scoreboardNote: 'O Pro acrescenta patrocinadores próprios, torneios automatizados, relatórios exportáveis, campanhas de PadCoins e notificações segmentadas.', scoreboardAria: 'Placar digital do Padbol Match durante uma partida', scoreboardCaption: 'Placar disponível atualmente no Padbol Match.',
  multisportEyebrow: 'UM CLUBE. QUATRO ESPORTES.', multisportTitle: 'Padbol · Padel · Pickleball · Tênis', multisportText: 'Administre todos os seus Padbol Courts e as demais quadras em uma só plataforma, mesmo que o clube ofereça diferentes esportes.',
  automationEyebrow: 'STARTER ADMINISTRA. PRO AUTOMATIZA.', automationTitle: 'Mais movimento para o seu clube.', automationAccent: 'Menos tarefas repetitivas.', automation: [['Torneios automatizados', 'Sorteio → grupos → partidas → resultados → classificação → chaves → finais.'], ['Gere novas receitas', 'Planos de associação, promoções e espaços próprios para patrocinadores.'], ['Fidelize os jogadores', 'PadCoins, campanhas e benefícios configurados pelo clube.'], ['Reduza o custo da plataforma', 'Starter: 1% · Pro: 0,65%. Valores ajustáveis por região.']],
  migrationEyebrow: 'JÁ USA OUTRO SISTEMA?', migrationTitle: 'Você não começa do zero.', migrationText: 'Podemos importar informações que pertençam legitimamente ao clube e estejam em formato compatível. O escopo é validado antes do início.', migration: [['Starter', 'Importação de arquivos compatíveis, sujeita a validação.'], ['Pro', 'Migração assistida.'], ['Business', 'Migração personalizada.']],
  growthAria: 'Ferramentas de crescimento do Pro', membershipTitle: 'CRIE SEU PRÓPRIO PLANO DE ASSOCIAÇÃO', membershipText: 'Defina preço, duração, benefícios, descontos, horários, prioridade, reservas incluídas e PadCoins. É um plano próprio do clube, separado de qualquer futura assinatura global do jogador.', screensTitle: 'TRANSFORME SUAS TELAS EM UM ATIVO', screensText: 'Administre seus próprios patrocinadores no placar, na TV, nos torneios e nos espaços locais disponíveis. O inventário do clube permanece separado dos inventários Global Padbol Match e FIPA.',
  experiencesEyebrow: 'CINCO EXPERIÊNCIAS. UM SÓ PRODUTO.', experiencesText: 'São interfaces visuais do Padbol Match. Não são planos comerciais e não determinam se o clube usa Starter, Pro ou Business.', finalTitle: 'Comece sem custo fixo.', finalAccent: 'A operação continua sendo sua.', talk: 'VAMOS CONVERSAR',
  plans: {
    starter: { courtsLabel: 'Até 4 quadras', adminsLabel: '1 administrador', summary: 'Para clubes com até 4 quadras que querem administrar a operação sem mensalidade.', ctaLabel: 'COMEÇAR SEM MENSALIDADE', features: ['Padbol, Padel, Pickleball e Tênis', 'Jogadores e clientes ilimitados', 'Perfil público do clube, quadras, horários, tarifas e disponibilidade', 'Reservas online e lançamento manual de reservas', 'Partidas, registro de resultados e ranking do clube', 'Torneios administrados pelo clube: inscrições, equipes, partidas e resultados', 'Placar digital com controle ao vivo e exibição em tela ou TV', 'Painel operacional de reservas, ocupação e receitas', 'Saldos, movimentações e resgates de PadCoins do clube', 'Importação de arquivos compatíveis, sujeita a validação prévia'] },
    pro: { courtsLabel: 'Até 12 quadras', adminsLabel: 'Até 5 administradores', summary: 'Para clubes que querem automatizar a operação e ampliar sua comunidade.', ctaLabel: 'ESCOLHER PRO', features: ['Tudo do Starter', 'Torneios automatizados: sorteios, grupos, tabela, classificação, chaves e pódios', 'Relatórios e exportações de reservas, receitas e PadCoins', 'Listas de espera de torneios e avisos de abertura', 'Campanhas, promoções, prêmios e resgates com PadCoins', 'Planos de associação próprios do clube', 'Patrocinadores próprios no placar, nos torneios e nas telas do clube', 'Notificações segmentadas aos jogadores do clube', 'Migração assistida e suporte prioritário'] },
    business: { pricePrefix: 'A partir de', commissionPrefix: 'A partir de', courtsLabel: '13 ou mais quadras', adminsLabel: 'Condições personalizadas', summary: 'Soluções multiclube e personalizadas para redes, operadores e licenciados.', ctaLabel: 'VAMOS CONVERSAR', features: ['Tudo do Pro', 'Escopo multiclube definido com cada organização', 'Permissões e administração centralizadas conforme o projeto', 'Relatórios consolidados e campanhas de rede conforme o escopo', 'Migração personalizada', 'Integrações e API sujeitas a validação técnica', 'Suporte dedicado'] },
  },
};

const PT_PT = {
  ...PT_BR,
  metaDescription: 'O Padbol Match reúne reservas, jogadores, jogos, torneios, rankings, marcador digital e gestão de clubes multidesportivos.',
  title: 'Todo o seu clube.', sports: 'Padbol · Padel · Pickleball · Ténis', lead: 'Reservas, jogadores, jogos, torneios, rankings, marcador em direto, adesões e gestão num só lugar.',
  liveClub: 'CLUBE EM DIRETO', liveMatch: 'Jogo e marcador em direto', connected: 'Uma operação integrada antes, durante e depois de jogar.',
  playerFeeTitle: 'O JOGADOR PAGA 0% DE COMISSÃO AO PADBOL MATCH.', playerFeeText: 'As comissões dos planos correspondem ao serviço prestado ao clube. Os custos do Stripe ou de outro processador de pagamentos são cobrados separadamente.',
  padbolOwnerTitle: 'É proprietário de um ou mais Padbol Courts?', padbolOwnerText: 'Solicite o Padbol Match Pro gratuitamente durante 12 meses e faça a gestão do clube numa só plataforma.', padbolOwnerHint: 'Fale-nos do seu clube. A nossa equipa entrará em contacto para analisar o pedido e os próximos passos.',
  plansTitle: 'Comece pela gestão.', plansAccent: 'Passe para Pro para automatizar.', scoreboardTitle: 'O jogo em direto.', scoreboardItems: ['Resultado e atualizações em direto.', 'Apresentação num ecrã ou TV.', 'Controlo sem fios a partir dos dispositivos do clube.'],
  devices: 'Telemóvel · Tablet · Computador · TV', multisportTitle: 'Padbol · Padel · Pickleball · Ténis', multisportText: 'Faça a gestão de todos os seus Padbol Courts e dos restantes campos na mesma plataforma, mesmo que o clube ofereça diferentes desportos.',
  automationTitle: 'Mais atividade para o seu clube.', automationAccent: 'Menos tarefas repetitivas.',
  migrationTitle: 'Não começa do zero.', migrationText: 'Podemos importar informações que pertençam legitimamente ao clube e estejam num formato compatível. O âmbito é validado antes de começar.',
  membershipTitle: 'CRIE A SUA PRÓPRIA ADESÃO', membershipText: 'Defina preço, duração, benefícios, descontos, horários, prioridade, reservas incluídas e PadCoins. É uma adesão própria do clube, separada de qualquer futura adesão global do jogador.',
  finalTitle: 'Comece sem custo fixo.', finalAccent: 'A operação continua a ser sua.',
  plans: {
    starter: { ...PT_BR.plans.starter, courtsLabel: 'Até 4 campos', summary: 'Para clubes com até 4 campos que querem gerir a operação sem mensalidade.', features: ['Padbol, Padel, Pickleball e Ténis', 'Jogadores e clientes ilimitados', 'Perfil público do clube, campos, horários, preços e disponibilidade', 'Reservas online e registo manual de reservas', 'Jogos, registo de resultados e ranking do clube', 'Torneios geridos pelo clube: inscrições, equipas, jogos e resultados', 'Marcador digital com controlo em direto e apresentação num ecrã ou TV', 'Painel operacional de reservas, ocupação e receitas', 'Saldos, movimentos e utilizações de PadCoins do clube', 'Importação de ficheiros compatíveis, sujeita a validação prévia'] },
    pro: { ...PT_BR.plans.pro, courtsLabel: 'Até 12 campos', summary: 'Para clubes que querem automatizar a operação e desenvolver a sua comunidade.', features: ['Tudo o que inclui o Starter', 'Torneios automatizados: sorteios, grupos, calendário, classificação, eliminatórias e pódios', 'Relatórios e exportações de reservas, receitas e PadCoins', 'Listas de espera de torneios e avisos de abertura', 'Campanhas, promoções, prémios e utilizações de PadCoins', 'Adesões próprias do clube', 'Patrocinadores próprios no marcador, nos torneios e nos ecrãs do clube', 'Notificações segmentadas aos jogadores do clube', 'Migração assistida e apoio prioritário'] },
    business: { ...PT_BR.plans.business, courtsLabel: '13 ou mais campos', summary: 'Soluções para vários clubes e à medida para redes, operadores e licenciados.', features: ['Tudo o que inclui o Pro', 'Âmbito multiclube definido com cada organização', 'Permissões e administração centralizadas conforme o projeto', 'Relatórios consolidados e campanhas de rede conforme o âmbito', 'Migração personalizada', 'Integrações e API sujeitas a validação técnica', 'Apoio dedicado'] },
  },
};

const IT = {
  ...EN,
  metaTitle: 'Padbol Match per i club — Piani', metaDescription: 'Padbol Match riunisce prenotazioni, giocatori, partite, tornei, classifiche, tabellone digitale e gestione dei club multisport.',
  notDefined: 'Da definire', featured: 'PIÙ SCELTO', perMonth: '/ mese', or: 'oppure', perYear: '/ anno', limits: 'Limiti del piano', venueService: 'Servizio per il club', commissionNote: 'sulle operazioni elaborate tramite Padbol Match',
  draft: 'BOZZA INTERNA · NON PUBBLICATA', back: '← Per gli amministratori', eyebrow: 'PADBOL MATCH PER I CLUB', title: 'Tutto il tuo club.', titleAccent: 'Un’unica piattaforma.', sports: 'Padbol · Padel · Pickleball · Tennis', lead: 'Prenotazioni, giocatori, partite, tornei, classifiche, tabellone in diretta, abbonamenti e gestione in un unico spazio.', start: 'INIZIA SENZA CANONE', seePlans: 'VEDI I PIANI', operationAria: 'Gestione connessa del club', liveClub: 'CLUB IN DIRETTA', fourSports: '4 sport', bookings: 'Prenotazioni e disponibilità', liveMatch: 'Partita e tabellone in diretta', results: 'Risultati, classifica e ritorno dei giocatori', connected: 'Un’unica gestione connessa prima, durante e dopo il gioco.',
  playerFeeAria: 'Commissioni per il giocatore', playerFeeTitle: 'IL GIOCATORE PAGA LO 0% DI COMMISSIONI A PADBOL MATCH.', playerFeeText: 'Le commissioni dei piani riguardano il servizio fornito al club. I costi di Stripe o di altri gestori dei pagamenti sono separati.',
  padbolBenefit: 'VANTAGGIO ESCLUSIVO PER I CLUB DI PADBOL', padbolOwnerTitle: 'Gestisci uno o più Padbol Courts?', padbolOwnerText: 'Richiedi Padbol Match Pro gratis per 12 mesi e gestisci il tuo club da un’unica piattaforma.', padbolOwnerHint: 'Raccontaci del tuo club. Il nostro team ti contatterà per valutare la richiesta e i passaggi successivi.', padbolOwnerCta: 'RICHIEDI 12 MESI DI PRO',
  plansEyebrow: 'PIANI CHE CRESCONO CON TE', plansTitle: 'Inizia dalla gestione.', plansAccent: 'Passa a Pro per automatizzare.', finePrint: 'Limiti, prezzi, promozioni e commissioni dipendono dalla regione e dalla configurazione vigente. Le condizioni Business vengono definite tramite contatto commerciale e verifica tecnica.',
  scoreboardEyebrow: 'IL TUO TABELLONE DIGITALE, INCLUSO GIÀ IN STARTER', scoreboardTitle: 'La partita in diretta.', scoreboardAccent: 'Senza attrezzatura specifica.', devices: 'Telefono · Tablet · Computer · TV', scoreboardItems: ['Punteggio e aggiornamenti in diretta.', 'Visualizzazione su schermo o TV.', 'Controllo wireless dai dispositivi del club.'], scoreboardNote: 'Pro aggiunge sponsor propri, tornei automatizzati, report esportabili, campagne PadCoins e notifiche segmentate.', scoreboardAria: 'Tabellone digitale Padbol Match durante una partita', scoreboardCaption: 'Tabellone attualmente disponibile in Padbol Match.',
  multisportEyebrow: 'UN CLUB. QUATTRO SPORT.', multisportTitle: 'Padbol · Padel · Pickleball · Tennis', multisportText: 'Gestisci tutti i tuoi Padbol Courts e gli altri campi da un’unica piattaforma, anche se il club propone sport diversi.',
  automationEyebrow: 'STARTER GESTISCE. PRO AUTOMATIZZA.', automationTitle: 'Più attività per il tuo club.', automationAccent: 'Meno operazioni ripetitive.', automation: [['Tornei automatizzati', 'Sorteggio → gironi → partite → risultati → classifica → tabellone → finali.'], ['Crea nuove entrate', 'Abbonamenti, promozioni e spazi propri per gli sponsor.'], ['Fidelizza i giocatori', 'PadCoins, campagne e vantaggi configurati dal club.'], ['Riduci il costo della piattaforma', 'Starter: 1% · Pro: 0,65%. Valori gestibili per regione.']],
  migrationEyebrow: 'USI GIÀ UN ALTRO SISTEMA?', migrationTitle: 'Non parti da zero.', migrationText: 'Possiamo importare informazioni che appartengono legittimamente al club e hanno un formato compatibile. L’ambito viene verificato prima di iniziare.', migration: [['Starter', 'Importazione di file compatibili, previa verifica.'], ['Pro', 'Migrazione assistita.'], ['Business', 'Migrazione personalizzata.']],
  growthAria: 'Strumenti Pro per la crescita', membershipTitle: 'CREA IL TUO ABBONAMENTO', membershipText: 'Definisci prezzo, durata, vantaggi, sconti, orari, priorità, prenotazioni incluse e PadCoins. È un abbonamento proprio del club, separato da qualsiasi futuro abbonamento globale del giocatore.', screensTitle: 'TRASFORMA I TUOI SCHERMI IN UNA RISORSA', screensText: 'Gestisci i tuoi sponsor sul tabellone, sulla TV, nei tornei e negli spazi locali disponibili. L’inventario del club rimane separato da quello Global Padbol Match e da quello FIPA.',
  experiencesEyebrow: 'CINQUE ESPERIENZE. UN SOLO PRODOTTO.', experiencesText: 'Sono interfacce visive di Padbol Match. Non sono piani commerciali e non determinano se un club usa Starter, Pro o Business.', finalTitle: 'Inizia senza costi fissi.', finalAccent: 'La gestione resta nelle tue mani.', talk: 'PARLIAMONE',
  plans: {
    starter: { courtsLabel: 'Fino a 4 campi', adminsLabel: '1 amministratore', summary: 'Per club con un massimo di 4 campi che vogliono gestire l’attività senza canone mensile.', ctaLabel: 'INIZIA SENZA CANONE', features: ['Padbol, Padel, Pickleball e Tennis', 'Giocatori e clienti illimitati', 'Profilo pubblico del club, campi, orari, tariffe e disponibilità', 'Prenotazioni online e inserimento manuale delle prenotazioni', 'Partite, inserimento dei risultati e classifica del club', 'Tornei gestiti dal club: iscrizioni, squadre, partite e risultati', 'Tabellone digitale con controllo in diretta e uscita su schermo o TV', 'Pannello operativo per prenotazioni, occupazione ed entrate', 'Saldi, movimenti e utilizzi dei PadCoins del club', 'Importazione di file compatibili, previa verifica'] },
    pro: { courtsLabel: 'Fino a 12 campi', adminsLabel: 'Fino a 5 amministratori', summary: 'Per i club che vogliono automatizzare la gestione e far crescere la propria comunità.', ctaLabel: 'SCEGLI PRO', features: ['Tutto ciò che include Starter', 'Tornei automatizzati: sorteggi, gironi, calendario, classifica, tabelloni e podi', 'Report ed esportazioni di prenotazioni, entrate e PadCoins', 'Liste d’attesa dei tornei e avvisi di apertura', 'Campagne, promozioni, premi e utilizzi dei PadCoins', 'Abbonamenti propri del club', 'Sponsor propri sul tabellone, nei tornei e sugli schermi del club', 'Notifiche segmentate ai giocatori del club', 'Migrazione assistita e assistenza prioritaria'] },
    business: { pricePrefix: 'Da', commissionPrefix: 'Da', courtsLabel: '13 o più campi', adminsLabel: 'Condizioni personalizzate', summary: 'Soluzioni multisede e personalizzate per catene, operatori e licenziatari.', ctaLabel: 'PARLIAMONE', features: ['Tutto ciò che include Pro', 'Ambito multisede definito con ogni organizzazione', 'Permessi e amministrazione centralizzati in base al progetto', 'Report consolidati e campagne di rete in base all’ambito', 'Migrazione personalizzata', 'Integrazioni e API soggette a verifica tecnica', 'Assistenza dedicata'] },
  },
};

const FR = {
  ...EN,
  metaTitle: 'Padbol Match pour les clubs — Offres', metaDescription: 'Padbol Match réunit réservations, joueurs, matchs, tournois, classements, tableau de score numérique et gestion de clubs multisports.',
  notDefined: 'À définir', featured: 'LE PLUS CHOISI', perMonth: '/ mois', or: 'ou', perYear: '/ an', limits: 'Limites de l’offre', venueService: 'Service pour le club', commissionNote: 'sur les opérations traitées par Padbol Match',
  draft: 'VERSION INTERNE · NON PUBLIÉE', back: '← Pour les administrateurs', eyebrow: 'PADBOL MATCH POUR LES CLUBS', title: 'Tout votre club.', titleAccent: 'Une seule plateforme.', sports: 'Padbol · Padel · Pickleball · Tennis', lead: 'Réservations, joueurs, matchs, tournois, classements, tableau de score en direct, abonnements et gestion au même endroit.', start: 'COMMENCER SANS ABONNEMENT', seePlans: 'VOIR LES OFFRES', operationAria: 'Fonctionnement connecté du club', liveClub: 'CLUB EN DIRECT', fourSports: '4 sports', bookings: 'Réservations et disponibilités', liveMatch: 'Match et tableau de score en direct', results: 'Résultats, classement et retour des joueurs', connected: 'Un fonctionnement connecté avant, pendant et après le jeu.',
  playerFeeAria: 'Frais pour le joueur', playerFeeTitle: 'LE JOUEUR PAIE 0 % DE COMMISSION À PADBOL MATCH.', playerFeeText: 'Les commissions des offres correspondent au service fourni au club. Les frais de Stripe ou de tout autre prestataire de paiement sont indépendants.',
  padbolBenefit: 'AVANTAGE EXCLUSIF POUR LES CLUBS DE PADBOL', padbolOwnerTitle: 'Gérez-vous un ou plusieurs Padbol Courts ?', padbolOwnerText: 'Demandez Padbol Match Pro gratuitement pendant 12 mois et gérez votre club depuis une seule plateforme.', padbolOwnerHint: 'Présentez-nous votre club. Notre équipe vous contactera pour étudier la demande et les prochaines étapes.', padbolOwnerCta: 'DEMANDER 12 MOIS DE PRO',
  plansEyebrow: 'DES OFFRES QUI ÉVOLUENT AVEC VOUS', plansTitle: 'Commencez par gérer.', plansAccent: 'Passez à Pro pour automatiser.', finePrint: 'Les limites, tarifs, promotions et commissions dépendent de la région et de la configuration en vigueur. Les conditions Business sont définies après échange commercial et validation technique.',
  scoreboardEyebrow: 'VOTRE TABLEAU DE SCORE NUMÉRIQUE, INCLUS DÈS STARTER', scoreboardTitle: 'Le match en direct.', scoreboardAccent: 'Sans équipement spécifique.', devices: 'Téléphone · Tablette · Ordinateur · TV', scoreboardItems: ['Score et mises à jour en direct.', 'Affichage sur écran ou téléviseur.', 'Contrôle sans fil depuis les appareils du club.'], scoreboardNote: 'Pro ajoute vos propres sponsors, les tournois automatisés, les rapports exportables, les campagnes PadCoins et les notifications ciblées.', scoreboardAria: 'Tableau de score numérique Padbol Match pendant un match', scoreboardCaption: 'Tableau de score actuellement disponible dans Padbol Match.',
  multisportEyebrow: 'UN CLUB. QUATRE SPORTS.', multisportTitle: 'Padbol · Padel · Pickleball · Tennis', multisportText: 'Gérez tous vos Padbol Courts et vos autres terrains depuis la même plateforme, même si votre club propose plusieurs sports.',
  automationEyebrow: 'STARTER GÈRE. PRO AUTOMATISE.', automationTitle: 'Plus d’activité pour votre club.', automationAccent: 'Moins de tâches répétitives.', automation: [['Tournois automatisés', 'Tirage → groupes → matchs → résultats → classement → tableau → finales.'], ['Créez de nouveaux revenus', 'Abonnements, promotions et emplacements réservés à vos sponsors.'], ['Fidélisez les joueurs', 'PadCoins, campagnes et avantages configurés par le club.'], ['Réduisez le coût de la plateforme', 'Starter : 1 % · Pro : 0,65 %. Valeurs configurables par région.']],
  migrationEyebrow: 'VOUS UTILISEZ DÉJÀ UN AUTRE SYSTÈME ?', migrationTitle: 'Vous ne repartez pas de zéro.', migrationText: 'Nous pouvons importer les informations qui appartiennent légitimement au club et utilisent un format compatible. Le périmètre est validé avant le démarrage.', migration: [['Starter', 'Import de fichiers compatibles, sous réserve de validation.'], ['Pro', 'Migration accompagnée.'], ['Business', 'Migration personnalisée.']],
  growthAria: 'Outils de développement Pro', membershipTitle: 'CRÉEZ VOTRE PROPRE ABONNEMENT', membershipText: 'Définissez le prix, la durée, les avantages, les réductions, les horaires, la priorité, les réservations incluses et les PadCoins. Il s’agit de l’abonnement propre au club, distinct de tout futur abonnement mondial du joueur.', screensTitle: 'TRANSFORMEZ VOS ÉCRANS EN ACTIF', screensText: 'Gérez vos propres sponsors sur le tableau de score, les TV, les tournois et les emplacements locaux disponibles. L’inventaire du club reste séparé de ceux de Global Padbol Match et de la FIPA.',
  experiencesEyebrow: 'CINQ EXPÉRIENCES. UN SEUL PRODUIT.', experiencesText: 'Ce sont des interfaces visuelles Padbol Match. Elles ne constituent pas des offres commerciales et ne déterminent pas si un club utilise Starter, Pro ou Business.', finalTitle: 'Commencez sans frais fixes.', finalAccent: 'Le fonctionnement reste entre vos mains.', talk: 'ÉCHANGEONS',
  plans: {
    starter: { courtsLabel: 'Jusqu’à 4 terrains', adminsLabel: '1 administrateur', summary: 'Pour les clubs comptant jusqu’à 4 terrains qui souhaitent gérer leur activité sans abonnement mensuel.', ctaLabel: 'COMMENCER SANS ABONNEMENT', features: ['Padbol, Padel, Pickleball et Tennis', 'Joueurs et clients illimités', 'Profil public du club, terrains, horaires, tarifs et disponibilités', 'Réservations en ligne et saisie manuelle des réservations', 'Matchs, saisie des résultats et classement du club', 'Tournois gérés par le club : inscriptions, équipes, matchs et résultats', 'Tableau de score numérique avec contrôle en direct et sortie écran ou TV', 'Tableau de bord opérationnel des réservations, de l’occupation et des revenus', 'Soldes, mouvements et utilisations des PadCoins du club', 'Import de fichiers compatibles, sous réserve de validation préalable'] },
    pro: { courtsLabel: 'Jusqu’à 12 terrains', adminsLabel: 'Jusqu’à 5 administrateurs', summary: 'Pour les clubs qui souhaitent automatiser leur activité et développer leur communauté.', ctaLabel: 'CHOISIR PRO', features: ['Tout ce qui est inclus dans Starter', 'Tournois automatisés : tirages, groupes, calendrier, classement, tableaux et podiums', 'Rapports et exports des réservations, revenus et PadCoins', 'Listes d’attente des tournois et alertes d’ouverture', 'Campagnes, promotions, récompenses et utilisations des PadCoins', 'Abonnements propres au club', 'Sponsors propres sur le tableau de score, dans les tournois et sur les écrans du club', 'Notifications ciblées aux joueurs du club', 'Migration accompagnée et assistance prioritaire'] },
    business: { pricePrefix: 'À partir de', commissionPrefix: 'À partir de', courtsLabel: '13 terrains ou plus', adminsLabel: 'Conditions personnalisées', summary: 'Solutions multisites et personnalisées pour les réseaux, opérateurs et licenciés.', ctaLabel: 'ÉCHANGEONS', features: ['Tout ce qui est inclus dans Pro', 'Périmètre multisite défini avec chaque organisation', 'Autorisations et administration centralisées selon le projet', 'Rapports consolidés et campagnes de réseau selon le périmètre', 'Migration personnalisée', 'Intégrations et API soumises à validation technique', 'Assistance dédiée'] },
  },
};

const DE = {
  ...EN,
  metaTitle: 'Padbol Match für Clubs — Tarife', metaDescription: 'Padbol Match vereint Buchungen, Spieler, Matches, Turniere, Ranglisten, digitale Spielstandsanzeige und die Verwaltung von Multisport-Clubs.',
  notDefined: 'Noch festzulegen', featured: 'BELIEBTESTE WAHL', perMonth: '/ Monat', or: 'oder', perYear: '/ Jahr', limits: 'Tarifgrenzen', venueService: 'Service für den Club', commissionNote: 'auf Transaktionen, die über Padbol Match abgewickelt werden',
  draft: 'INTERNER ENTWURF · NICHT VERÖFFENTLICHT', back: '← Für Administratoren', eyebrow: 'PADBOL MATCH FÜR CLUBS', title: 'Ihr gesamter Club.', titleAccent: 'Eine Plattform.', sports: 'Padbol · Padel · Pickleball · Tennis', lead: 'Buchungen, Spieler, Matches, Turniere, Ranglisten, Live-Spielstand, Mitgliedschaften und Verwaltung an einem Ort.', start: 'OHNE MONATSGEBÜHR STARTEN', seePlans: 'TARIFE ANSEHEN', operationAria: 'Vernetzter Clubbetrieb', liveClub: 'CLUB LIVE', fourSports: '4 Sportarten', bookings: 'Buchungen und Verfügbarkeit', liveMatch: 'Live-Match und Spielstand', results: 'Ergebnisse, Rangliste und wiederkehrende Spieler', connected: 'Ein vernetzter Ablauf vor, während und nach dem Spiel.',
  playerFeeAria: 'Gebühren für Spieler', playerFeeTitle: 'SPIELER ZAHLEN 0 % PROVISION AN PADBOL MATCH.', playerFeeText: 'Die Provisionen der Tarife beziehen sich auf den Service für den Club. Kosten von Stripe oder anderen Zahlungsdienstleistern werden separat berechnet.',
  padbolBenefit: 'EXKLUSIVER VORTEIL FÜR PADBOL-CLUBS', padbolOwnerTitle: 'Betreiben Sie einen oder mehrere Padbol Courts?', padbolOwnerText: 'Beantragen Sie Padbol Match Pro für 12 Monate kostenlos und verwalten Sie Ihren Club auf einer einzigen Plattform.', padbolOwnerHint: 'Erzählen Sie uns von Ihrem Club. Unser Team meldet sich, um den Antrag und die nächsten Schritte zu besprechen.', padbolOwnerCta: '12 MONATE PRO BEANTRAGEN',
  plansEyebrow: 'TARIFE, DIE MIT IHNEN WACHSEN', plansTitle: 'Mit der Verwaltung beginnen.', plansAccent: 'Mit Pro automatisieren.', finePrint: 'Grenzen, Preise, Aktionen und Provisionen hängen von der Region und der aktuellen Konfiguration ab. Business-Konditionen werden im persönlichen Gespräch und nach technischer Prüfung festgelegt.',
  scoreboardEyebrow: 'IHRE DIGITALE SPIELSTANDSANZEIGE, AB STARTER INKLUSIVE', scoreboardTitle: 'Das Match live.', scoreboardAccent: 'Ohne Spezialausrüstung.', devices: 'Smartphone · Tablet · Computer · TV', scoreboardItems: ['Live-Spielstand und Aktualisierungen.', 'Anzeige auf Bildschirm oder TV.', 'Kabellose Steuerung über die Geräte des Clubs.'], scoreboardNote: 'Pro ergänzt eigene Sponsoren, automatisierte Turniere, exportierbare Berichte, PadCoins-Kampagnen und zielgerichtete Benachrichtigungen.', scoreboardAria: 'Digitale Padbol Match Spielstandsanzeige während eines Matches', scoreboardCaption: 'Derzeit in Padbol Match verfügbare Spielstandsanzeige.',
  multisportEyebrow: 'EIN CLUB. VIER SPORTARTEN.', multisportTitle: 'Padbol · Padel · Pickleball · Tennis', multisportText: 'Verwalten Sie alle Padbol Courts und weiteren Plätze auf einer Plattform, auch wenn Ihr Club mehrere Sportarten anbietet.',
  automationEyebrow: 'STARTER VERWALTET. PRO AUTOMATISIERT.', automationTitle: 'Mehr Aktivität für Ihren Club.', automationAccent: 'Weniger wiederkehrende Aufgaben.', automation: [['Automatisierte Turniere', 'Auslosung → Gruppen → Matches → Ergebnisse → Tabelle → K.-o.-Runde → Finale.'], ['Neue Einnahmen erzielen', 'Mitgliedschaften, Aktionen und eigene Werbeflächen für Sponsoren.'], ['Spieler langfristig binden', 'PadCoins, Kampagnen und vom Club festgelegte Vorteile.'], ['Plattformkosten senken', 'Starter: 1 % · Pro: 0,65 %. Werte können regional verwaltet werden.']],
  migrationEyebrow: 'SIE NUTZEN BEREITS EIN ANDERES SYSTEM?', migrationTitle: 'Sie beginnen nicht bei null.', migrationText: 'Wir können Daten importieren, die rechtmäßig dem Club gehören und in einem kompatiblen Format vorliegen. Der Umfang wird vor Beginn geprüft.', migration: [['Starter', 'Import kompatibler Dateien nach Prüfung.'], ['Pro', 'Begleitete Migration.'], ['Business', 'Individuelle Migration.']],
  growthAria: 'Pro-Wachstumswerkzeuge', membershipTitle: 'EIGENE MITGLIEDSCHAFT ERSTELLEN', membershipText: 'Legen Sie Preis, Laufzeit, Vorteile, Rabatte, Zeiten, Priorität, enthaltene Buchungen und PadCoins fest. Dies ist die eigene Mitgliedschaft des Clubs, getrennt von einer möglichen künftigen globalen Spielermitgliedschaft.', screensTitle: 'MACHEN SIE IHRE BILDSCHIRME ZUM WERTTRÄGER', screensText: 'Verwalten Sie eigene Sponsoren auf der Spielstandsanzeige, auf TVs, in Turnieren und auf verfügbaren lokalen Flächen. Das Inventar des Clubs bleibt von Global Padbol Match und FIPA getrennt.',
  experiencesEyebrow: 'FÜNF ERLEBNISSE. EIN PRODUKT.', experiencesText: 'Dies sind visuelle Oberflächen von Padbol Match. Sie sind keine Tarife und bestimmen nicht, ob ein Club Starter, Pro oder Business nutzt.', finalTitle: 'Ohne Fixkosten starten.', finalAccent: 'Der Betrieb bleibt in Ihren Händen.', talk: 'KONTAKT AUFNEHMEN',
  plans: {
    starter: { courtsLabel: 'Bis zu 4 Plätze', adminsLabel: '1 Administrator', summary: 'Für Clubs mit bis zu 4 Plätzen, die ihren Betrieb ohne Monatsgebühr verwalten möchten.', ctaLabel: 'OHNE MONATSGEBÜHR STARTEN', features: ['Padbol, Padel, Pickleball und Tennis', 'Unbegrenzte Anzahl an Spielern und Kunden', 'Öffentliches Clubprofil, Plätze, Öffnungszeiten, Preise und Verfügbarkeit', 'Online-Buchungen und manuelle Buchungserfassung', 'Matches, Ergebniserfassung und Clubrangliste', 'Vom Club verwaltete Turniere: Anmeldungen, Teams, Matches und Ergebnisse', 'Digitale Spielstandsanzeige mit Live-Steuerung und Ausgabe auf Bildschirm oder TV', 'Betriebsübersicht für Buchungen, Auslastung und Einnahmen', 'PadCoins-Guthaben, Bewegungen und Einlösungen des Clubs', 'Import kompatibler Dateien nach vorheriger Prüfung'] },
    pro: { courtsLabel: 'Bis zu 12 Plätze', adminsLabel: 'Bis zu 5 Administratoren', summary: 'Für Clubs, die ihren Betrieb automatisieren und ihre Community ausbauen möchten.', ctaLabel: 'PRO WÄHLEN', features: ['Alles aus Starter', 'Automatisierte Turniere: Auslosungen, Gruppen, Spielplan, Tabelle, K.-o.-Runden und Podien', 'Berichte und Exporte zu Buchungen, Einnahmen und PadCoins', 'Turnierwartelisten und Benachrichtigungen bei freien Plätzen', 'Kampagnen, Aktionen, Prämien und PadCoins-Einlösungen', 'Eigene Clubmitgliedschaften', 'Eigene Sponsoren auf Spielstandsanzeigen, in Turnieren und auf Clubbildschirmen', 'Zielgerichtete Benachrichtigungen an Clubspieler', 'Begleitete Migration und bevorzugter Support'] },
    business: { pricePrefix: 'Ab', commissionPrefix: 'Ab', courtsLabel: '13 oder mehr Plätze', adminsLabel: 'Individuelle Bedingungen', summary: 'Standortübergreifende und individuelle Lösungen für Ketten, Betreiber und Lizenznehmer.', ctaLabel: 'KONTAKT AUFNEHMEN', features: ['Alles aus Pro', 'Standortübergreifender Umfang gemeinsam mit jeder Organisation festgelegt', 'Zentralisierte Berechtigungen und Verwaltung nach Projekt', 'Konsolidierte Berichte und Netzwerkkampagnen nach vereinbartem Umfang', 'Individuelle Migration', 'Integrationen und API nach technischer Prüfung', 'Persönlicher Support'] },
  },
};

export function venuePlansCopy(language) {
  const code = String(language || '').toLowerCase();
  if (code.startsWith('es')) return ES;
  if (code.startsWith('ro')) return RO;
  if (code.startsWith('cs')) return CS;
  if (code.startsWith('pt-pt')) return PT_PT;
  if (code.startsWith('pt')) return PT_BR;
  if (code.startsWith('it')) return IT;
  if (code.startsWith('fr')) return FR;
  if (code.startsWith('de')) return DE;
  return EN;
}
