-- Reseñas públicas por sede (una por jugador autenticado por sede).
-- Ejecutar en Supabase SQL Editor (o migración) antes de usar POST/GET /api/sedes/:id/resenas.

create table if not exists public.sede_resenas (
  id bigint generated by default as identity primary key,
  sede_id integer not null references public.sedes (id) on delete cascade,
  user_id uuid not null,
  estrellas smallint not null check (estrellas >= 1 and estrellas <= 5),
  comentario text not null default '' check (char_length(comentario) <= 200),
  created_at timestamptz not null default now(),
  constraint sede_resenas_sede_usuario unique (sede_id, user_id)
);

create index if not exists idx_sede_resenas_sede_created
  on public.sede_resenas (sede_id, created_at desc);

comment on table public.sede_resenas is 'Reseñas con estrellas en perfil público de sede; el backend valida JWT.';
