-- =============================================================================
-- Reseñas públicas por sede (una por usuario autenticado por sede).
-- Ejecutar TODO este script en Supabase → SQL Editor (una sola vez).
--
-- Nombre de tabla: public.sede_resenas  (solo ASCII: letra n, SIN tilde ñ).
-- El backend y PostgREST usan exactamente este identificador; no crear
-- public.sede_reseñas ni variantes con ñ en el nombre del objeto SQL.
-- =============================================================================

create table if not exists public.sede_resenas (
  id bigint generated by default as identity primary key,
  sede_id integer not null references public.sedes (id) on delete cascade,
  user_id uuid not null,
  estrellas smallint not null check (estrellas >= 1 and estrellas <= 5),
  comentario text not null default '' check (char_length(comentario) <= 200),
  created_at timestamptz not null default now(),
  constraint sede_resenas_sede_usuario unique (sede_id, user_id)
);

create index if not exists idx_sede_resenas_sede_created
  on public.sede_resenas (sede_id, created_at desc);

comment on table public.sede_resenas is 'Reseñas con estrellas en perfil público de sede; el backend valida JWT. Tabla ASCII sede_resenas.';
