-- Historial de cambios de estado de reservas (auditoría admin / sistema / jugador).
-- Ejecutar en el SQL Editor de Supabase.

CREATE TABLE IF NOT EXISTS public.reservas_historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id bigint NOT NULL REFERENCES public.reservas (id) ON DELETE CASCADE,
  estado_anterior text,
  estado_nuevo text,
  changed_by text NOT NULL DEFAULT 'sistema',
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.reservas_historial IS 'Cada cambio de estado de una reserva: quién y cuándo.';
COMMENT ON COLUMN public.reservas_historial.changed_by IS 'Valores típicos: sistema | admin:email@... | jugador:email@...';

CREATE INDEX IF NOT EXISTS idx_reservas_historial_reserva_created
  ON public.reservas_historial (reserva_id, created_at DESC);
