create table if not exists public.recorridos_externos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  origen text not null,
  categorias text[] not null default '{}',
  comentario text,
  capturas_paths text[] not null default '{}',
  estado text not null default 'recibido' check (estado in ('recibido','en_revision','requiere_informacion','aprobado','rechazado')),
  datos_reconocidos jsonb not null default '{}'::jsonb,
  nota_revision text,
  revisar_antes_de timestamptz not null default (now() + interval '24 hours'),
  revisado_por uuid references auth.users(id) on delete set null,
  revisado_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recorridos_externos_user_created_idx
  on public.recorridos_externos (user_id, created_at desc);
create index if not exists recorridos_externos_estado_deadline_idx
  on public.recorridos_externos (estado, revisar_antes_de);
create unique index if not exists recorridos_externos_una_activa_por_jugador_idx
  on public.recorridos_externos (user_id)
  where estado in ('recibido', 'en_revision');

alter table public.recorridos_externos enable row level security;

drop policy if exists "jugador lee su recorrido externo" on public.recorridos_externos;
create policy "jugador lee su recorrido externo"
  on public.recorridos_externos for select
  using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'recorridos-externos',
  'recorridos-externos',
  false,
  8388608,
  array['image/jpeg','image/png','image/webp','application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.recorridos_externos is
  'Solicitudes de jugadores para reconocer recorrido deportivo previo; evidencia privada y revisión en hasta 24 horas.';
